import fs from 'fs';

const UI_TEXT = {
    "hi": {
        "10th House Karma": "दसवां घर कर्म",
        "11th House Bonds": "11वें सदन के बांड",
        "11th House Gains": "11वें घर में लाभ",
        "12th/5th House Release": "12वां/5वां घर रिलीज",
        "12th/9th House Vectors": "12वें/9वें घर के सदिश",
        "2nd House Sustenance": "द्वितीय भाव का भरण-पोषण",
        "3rd/5th House Skills": "तीसरे/पांचवें घर के कौशल",
        "4th House Mobility": "चतुर्थ भाव की गतिशीलता",
        "4th House Tranquility": "चतुर्थ भाव शांति",
        "6th House Afflictions": "छठे भाव का कष्ट",
        "6th House Companions": "छठे घर के साथी",
        "6th House Discipline": "छठा घर अनुशासन",
        "6th House Ledgers": "छठे सदन के बहीखाते",
        "6th/Saturn Karma": "छठा/शनि कर्म",
        "8th House Mysteries": "आठवें घर के रहस्य",
        "9th House Philanthropy": "नौवां घर परोपकार",
        "9th House Roots": "नौवें घर की जड़ें",
        "Afflictions demand propitiation. Which traditional remedial measure do you seek to enact?": "कष्ट प्रायश्चित की मांग करते हैं। आप कौन सा पारंपरिक उपचारात्मक उपाय लागू करना चाहते हैं?",
        "Arudha Lagna Profile": "अरुधा लग्न प्रोफ़ाइल",
        "Between the grinding gears of Dharma and Artha, the soul requires Vishrama (rest) and playful release to maintain sanity. How do you retreat?": "धर्म और अर्थ के पीसने के बीच, आत्मा को विवेक बनाए रखने के लिए विश्राम (विश्राम) और चंचल रिहाई की आवश्यकता होती है। आप कैसे पीछे हटते हैं?",
        "D12 Dwadasamsa": "डी12 द्वादशांश",
        "D2 Hora Liquidity": "D2 होरा तरलता",
        "D20 Vimsamsa": "डी20 विम्समसा",
        "D24 Chaturvimsamsa": "डी24 चतुर्विमसंसा",
        "D3 Drekkana": "डी3 ड्रेक्कना",
        "D30 Trimsamsa": "डी30 त्रिम्समसा",
        "D4 Chaturthamsa": "डी4 चतुर्थांश",
        "D40 Khavedamsa": "D40 खवेदमसा",
        "D6 Bodily Humors": "डी6 शारीरिक हास्य",
        "D60 Shashtiamsa": "डी60 षष्टीमसा",
        "D7 Saptamsa Matrix": "D7 सप्तमसा मैट्रिक्स",
        "D8 Ashtamsa Matrix": "डी8 अष्टमसा मैट्रिक्स",
        "D9 & 9th House Rectitude": "D9 और 9वें घर की शुद्धता",
        "D9 Navamsa Harmony": "डी9 नवांश समरसता",
        "Dosha Mitigation": "दोष शमन",
        "Maraka & Badhaka": "मराका और बधाका",
        "Muhurta aligns human action with divine time. What auspicious event are you planning?": "मुहूर्त मानवीय क्रिया को दैवीय समय के साथ संरेखित करता है। आप किस शुभ कार्यक्रम की योजना बना रहे हैं?",
        "Panchanga Engine": "पंचांग इंजन",
        "Swapna Shastra": "स्वप्न शास्त्र",
        "The 10th house governs your livelihood, daily trade, and standing before employers. What is the state of your work?": "दसवां घर आपकी आजीविका, दैनिक व्यापार और नियोक्ताओं के सामने आपकी स्थिति को नियंत्रित करता है। आपके काम की स्थिति क्या है?",
        "The 11th house dictates your ability to extract wealth and favors from large societies or guilds. What is the objective?": "11वां घर बड़े समाजों या संघों से धन और अनुग्रह प्राप्त करने की आपकी क्षमता को निर्धारित करता है। उद्देश्य क्या है?",
        "The 11th house signifies the networks and companions we choose. Are your friends true allies or hidden drains?": "11वां भाव हमारे द्वारा चुने गए नेटवर्क और साथियों को दर्शाता है। क्या आपके मित्र सच्चे सहयोगी या छुपे हुए नालियाँ हैं?",
        "The 2nd house and D2 chart govern accumulated treasures, gold, and grains. What is your material focus?": "दूसरा घर और डी2 चार्ट संचित खजाने, सोना और अनाज को नियंत्रित करते हैं। आपका भौतिक फोकस क्या है?",
        "The 2nd house rules what enters the mouth. Diet directly shapes consciousness and physical destiny. What are you consuming?": "दूसरा घर मुंह में प्रवेश करने वाली चीज़ को नियंत्रित करता है। आहार सीधे तौर पर चेतना और शारीरिक नियति को आकार देता है। आप क्या खा रहे हैं?",
        "The 3rd house governs the hands; the 5th governs creative intelligence. Are you honing your innate God-given skills?": "तीसरा घर हाथों को नियंत्रित करता है; 5वां रचनात्मक बुद्धि को नियंत्रित करता है। क्या आप ईश्वर प्रदत्त अपने जन्मजात कौशल को निखार रहे हैं?",
        "The 3rd house rules valor (Parakrama), siblings, and the right arm. Where is your courage directed?": "तीसरा घर पराक्रम, भाई-बहन और दाहिने हाथ को नियंत्रित करता है। आपका साहस कहाँ निर्देशित है?",
        "The 4th house and Venus dictate your comfort in travel, ownership of vehicles, beasts of burden, and daily transport. Is your carriage secure?": "चौथा घर और शुक्र यात्रा, वाहनों के स्वामित्व, बोझ उठाने वाले जानवरों और दैनिक परिवहन में आपकी सुविधा को निर्धारित करते हैं। क्या आपकी गाड़ी सुरक्षित है?",
        "The 4th house governs fixed assets, land, and the comfort of the home. What earthly matter arises?": "चौथा घर अचल संपत्ति, भूमि और घर के आराम को नियंत्रित करता है। कौन सा पार्थिव पदार्थ उत्पन्न होता है?",
        "The 6th house dictates your relation to hard physical labor, servants, employees, and those lower in the social hierarchy. How do you manage the toil?": "छठा घर कठिन शारीरिक श्रम, नौकरों, कर्मचारियों और सामाजिक पदानुक्रम में निचले लोगों के साथ आपके संबंध को निर्धारित करता है। आप परिश्रम का प्रबंधन कैसे करते हैं?",
        "The 6th house governs open enemies, disputes, and royal punishments. What conflict plagues you?": "छठा भाव खुले शत्रुओं, विवादों और शाही दंडों को नियंत्रित करता है। कौन सा संघर्ष आपको परेशान करता है?",
        "The 6th house requires the rhythmic discipline of daily life to suppress diseases and enemies. What needs correction?": "छठे भाव में रोगों और शत्रुओं को दबाने के लिए दैनिक जीवन के लयबद्ध अनुशासन की आवश्यकता होती है। सुधार की क्या आवश्यकता है?",
        "The 6th house rules Shadripu (the six enemies of the mind). Kama, Krodha, Lobha, Moha, Mada, Matsarya. Which vice has taken the reins?": "छठा घर शाद्रिपु (मन के छह शत्रु) पर शासन करता है। काम, क्रोध, लोभ, मोह, मद, मात्सर्य। किस वाइस ने लगाम ले ली है?",
        "The 6th house tracks the heavy karmic chains of Runa (Debt). Are you bound to creditors, or are others bound to you?": "छठा घर रूण (ऋण) की भारी कर्म श्रृंखलाओं को ट्रैक करता है। क्या आप लेनदारों से बंधे हैं, या अन्य लोग आपसे बंधे हैं?",
        "The 8th house and D8 chart govern Tantra, hidden dimension, and the manipulation of occult energies. Do you dare look?": "आठवां घर और डी8 चार्ट तंत्र, छिपे हुए आयाम और गुप्त ऊर्जा के हेरफेर को नियंत्रित करते हैं। क्या तुममें देखने की हिम्मत है?",
        "The 8th house rules unearned wealth, buried treasures, and sudden reversals. What hidden matter stirs?": "आठवां घर अनर्जित धन, गड़े हुए खजाने और अचानक उलटफेर को नियंत्रित करता है। कौन सी छुपी हुई बात हलचल मचाती है?",
        "The 9th house connects you to the deep, unshakable roots of your ancestors, language, and cultural rituals. Are you tethered or drifting?": "नौवां घर आपको आपके पूर्वजों, भाषा और सांस्कृतिक रीति-रिवाजों की गहरी, अटल जड़ों से जोड़ता है। क्या आप बंधे हुए हैं या बह रहे हैं?",
        "The Arudha Lagna dictates the Maya—how the world perceives your status and renown. What is your public aim?": "अरुधा लग्न माया को निर्देशित करता है - दुनिया आपकी स्थिति और प्रसिद्धि को कैसे देखती है। आपका सार्वजनिक उद्देश्य क्या है?",
        "The D12 chart reveals the absolute karmic ties to the mother and father. What is the inquiry?": "डी12 चार्ट माता और पिता के साथ पूर्ण कार्मिक संबंधों को दर्शाता है। पूछताछ क्या है?",
        "The D20 charts your spiritual receptivity and readiness for Mantra Diksha. Are you prepared to receive?": "D20 मंत्र दीक्षा के लिए आपकी आध्यात्मिक ग्रहणशीलता और तत्परता को दर्शाता है। क्या आप प्राप्त करने के लिए तैयार हैं?",
        "The D6 map exposes imbalances in the Vata, Pitta, and Kapha doshas. What anomaly requires attention?": "D6 मानचित्र वात, पित्त और कफ दोषों में असंतुलन को उजागर करता है। किस विसंगति पर ध्यान देने की आवश्यकता है?",
        "The Maraka (Death-inflicting) houses command periods of immense physical danger. Scan for immediate threats.": "मारक (मृत्यु देने वाले) घर अत्यधिक शारीरिक खतरे की अवधि का आदेश देते हैं। तत्काल खतरों के लिए स्कैन करें.",
        "The expansion of the bloodline is governed by the 5th house. What concerns the legacy of your lineage?": "रक्तरेखा का विस्तार पंचम भाव से नियंत्रित होता है। आपके वंश की विरासत से क्या सरोकार है?",
        "The foundation of life rests upon Righteousness (Dharma). Which aspect of duty seeks clarity?": "जीवन की नींव धार्मिकता (धर्म) पर टिकी हुई है। कर्तव्य का कौन सा पहलू स्पष्टता चाहता है?",
        "The management of beasts, pets, and agricultural livestock falls under the 6th house. How is your relationship with the silent beings?": "जानवरों, पालतू जानवरों और कृषि पशुधन का प्रबंधन छठे घर के अंतर्गत आता है। मूक प्राणियों के साथ आपका रिश्ता कैसा है?",
        "The pursuit of Vidya removes darkness. What intellectual or spiritual knowledge do you seek?": "विद्या की खोज अंधकार को दूर करती है। आप कौन सा बौद्धिक या आध्यात्मिक ज्ञान चाहते हैं?",
        "The sacred union of Vivaha binds two souls karmically. What is your inquiry regarding marital bonds?": "विवाह का पवित्र मिलन दो आत्माओं को कर्म से बांधता है। वैवाहिक बंधन के संबंध में आपकी क्या पूछताछ है?",
        "The subconscious mind receives signals from the astral plane. What omens are manifesting?": "अवचेतन मन सूक्ष्म तल से संकेत प्राप्त करता है। क्या शकुन प्रकट हो रहे हैं?",
        "The ultimate aim is liberation from the cycle of birth and death. What blocks your spiritual ascent?": "अंतिम लक्ष्य जन्म और मृत्यु के चक्र से मुक्ति है। आपकी आध्यात्मिक उन्नति में क्या बाधा है?",
        "Travel for spiritual merit or foreign expansion requires alignment. What is the nature of the journey?": "आध्यात्मिक योग्यता या विदेशी विस्तार के लिए यात्रा के लिए संरेखण की आवश्यकता होती है। यात्रा का स्वरूप क्या है?",
        "True wealth is internal peace (Sukha) and a harmonious home. What disturbs the waters of the mind?": "सच्चा धन आंतरिक शांति (सुखा) और एक सामंजस्यपूर्ण घर है। मन के जल को क्या विक्षुब्ध करता है?",
        "We carry the unsolved debts of our forefathers. What ancestral affliction requires propitiation?": "हम अपने पूर्वजों का अनसुलझा कर्ज ढो रहे हैं। किस पैतृक क्लेश के लिए प्रायश्चित की आवश्यकता होती है?",
        "Wealth that is hoarded rots the soul. Danam (Charity) is the great purifier of the D2 treasury. Where must your resources flow?": "संग्रहित किया हुआ धन आत्मा को गला देता है। दानम (दान) डी2 कोष का महान शोधक है। आपके संसाधन कहाँ प्रवाहित होने चाहिए?"
    },
    "kn": {
        "10th House Karma": "10 ನೇ ಮನೆ ಕರ್ಮ",
        "11th House Bonds": "11 ನೇ ಹೌಸ್ ಬಾಂಡ್‌ಗಳು",
        "11th House Gains": "11 ನೇ ಮನೆ ಲಾಭ",
        "12th/5th House Release": "12ನೇ/5ನೇ ಮನೆ ಬಿಡುಗಡೆ",
        "12th/9th House Vectors": "12ನೇ/9ನೇ ಹೌಸ್ ವೆಕ್ಟರ್ಸ್",
        "2nd House Sustenance": "2 ನೇ ಮನೆ ಜೀವನಾಂಶ",
        "3rd/5th House Skills": "3ನೇ/5ನೇ ಮನೆ ಕೌಶಲ್ಯಗಳು",
        "4th House Mobility": "4 ನೇ ಹೌಸ್ ಮೊಬಿಲಿಟಿ",
        "4th House Tranquility": "4 ನೇ ಮನೆಯ ಶಾಂತಿ",
        "6th House Afflictions": "6 ನೇ ಮನೆಯ ಬಾಧೆಗಳು",
        "6th House Companions": "6 ನೇ ಮನೆಯ ಸಹಚರರು",
        "6th House Discipline": "6 ನೇ ಮನೆ ಶಿಸ್ತು",
        "6th House Ledgers": "6 ನೇ ಹೌಸ್ ಲೆಡ್ಜರ್ಸ್",
        "6th/Saturn Karma": "6ನೇ/ಶನಿ ಕರ್ಮ",
        "8th House Mysteries": "8 ನೇ ಮನೆಯ ರಹಸ್ಯಗಳು",
        "9th House Philanthropy": "9 ನೇ ಮನೆ ಲೋಕೋಪಕಾರ",
        "9th House Roots": "9 ನೇ ಮನೆಯ ಬೇರುಗಳು",
        "Afflictions demand propitiation. Which traditional remedial measure do you seek to enact?": "ಸಂಕಟಗಳು ಪ್ರಾಯಶ್ಚಿತ್ತವನ್ನು ಬೇಡುತ್ತವೆ. ನೀವು ಯಾವ ಸಾಂಪ್ರದಾಯಿಕ ಪರಿಹಾರ ಕ್ರಮವನ್ನು ಜಾರಿಗೆ ತರಲು ಬಯಸುತ್ತೀರಿ?",
        "Arudha Lagna Profile": "ಆರೂಢ ಲಗ್ನ ವಿವರ",
        "Between the grinding gears of Dharma and Artha, the soul requires Vishrama (rest) and playful release to maintain sanity. How do you retreat?": "ಧರ್ಮ ಮತ್ತು ಅರ್ಥದ ಗ್ರೈಂಡಿಂಗ್ ಗೇರ್‌ಗಳ ನಡುವೆ, ವಿವೇಕವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಲು ಆತ್ಮಕ್ಕೆ ವಿಶ್ರಾಮ (ವಿಶ್ರಾಂತಿ) ಮತ್ತು ತಮಾಷೆಯ ಬಿಡುಗಡೆಯ ಅಗತ್ಯವಿರುತ್ತದೆ. ನೀವು ಹೇಗೆ ಹಿಮ್ಮೆಟ್ಟುತ್ತೀರಿ?",
        "D12 Dwadasamsa": "D12 ದ್ವಾದಶಾಂಶ",
        "D2 Hora Liquidity": "D2 ಹೋರಾ ಲಿಕ್ವಿಡಿಟಿ",
        "D20 Vimsamsa": "D20 Vimsamsa",
        "D24 Chaturvimsamsa": "D24 ಚತುರ್ವಿಂಸಂಸ",
        "D3 Drekkana": "D3 ಡ್ರೆಕ್ಕಾನಾ",
        "D30 Trimsamsa": "D30 ತ್ರಿಮ್ಸಂಸ",
        "D4 Chaturthamsa": "D4 ಚತುರ್ಥಾಂಶ",
        "D40 Khavedamsa": "D40 ಖವೇದಂಸ",
        "D6 Bodily Humors": "D6 ದೈಹಿಕ ಹಾಸ್ಯಗಳು",
        "D60 Shashtiamsa": "D60 ಷಷ್ಟಿಯಾಂಶ",
        "D7 Saptamsa Matrix": "D7 ಸಪ್ತಾಂಶ ಮಾತೃಕೆ",
        "D8 Ashtamsa Matrix": "D8 ಅಷ್ಟಮಸ ಮ್ಯಾಟ್ರಿಕ್ಸ್",
        "D9 & 9th House Rectitude": "D9 ಮತ್ತು 9 ನೇ ಹೌಸ್ ರೆಕ್ಟಿಟ್ಯೂಡ್",
        "D9 Navamsa Harmony": "D9 ನವಾಂಶ ಸಾಮರಸ್ಯ",
        "Dosha Mitigation": "ದೋಷ ತಗ್ಗಿಸುವಿಕೆ",
        "Maraka & Badhaka": "ಮರಕ & ಬಾಧಕ",
        "Muhurta aligns human action with divine time. What auspicious event are you planning?": "ಮುಹೂರ್ತವು ಮಾನವ ಕ್ರಿಯೆಯನ್ನು ದೈವಿಕ ಸಮಯದೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ. ನೀವು ಯಾವ ಶುಭ ಕಾರ್ಯಕ್ರಮವನ್ನು ಯೋಜಿಸುತ್ತಿದ್ದೀರಿ?",
        "Panchanga Engine": "ಪಂಚಾಂಗ ಇಂಜಿನ್",
        "Swapna Shastra": "ಸ್ವಪ್ನ ಶಾಸ್ತ್ರ",
        "The 10th house governs your livelihood, daily trade, and standing before employers. What is the state of your work?": "10 ನೇ ಮನೆಯು ನಿಮ್ಮ ಜೀವನೋಪಾಯ, ದೈನಂದಿನ ವ್ಯಾಪಾರ ಮತ್ತು ಉದ್ಯೋಗದಾತರ ಮುಂದೆ ನಿಲ್ಲುತ್ತದೆ. ನಿಮ್ಮ ಕೆಲಸದ ಸ್ಥಿತಿ ಏನು?",
        "The 11th house dictates your ability to extract wealth and favors from large societies or guilds. What is the objective?": "11 ನೇ ಮನೆಯು ದೊಡ್ಡ ಸಮಾಜಗಳು ಅಥವಾ ಸಂಘಗಳಿಂದ ಸಂಪತ್ತು ಮತ್ತು ಅನುಕೂಲಗಳನ್ನು ಹೊರತೆಗೆಯುವ ನಿಮ್ಮ ಸಾಮರ್ಥ್ಯವನ್ನು ನಿರ್ದೇಶಿಸುತ್ತದೆ. ಉದ್ದೇಶವೇನು?",
        "The 11th house signifies the networks and companions we choose. Are your friends true allies or hidden drains?": "11 ನೇ ಮನೆಯು ನಾವು ಆಯ್ಕೆ ಮಾಡುವ ನೆಟ್‌ವರ್ಕ್‌ಗಳು ಮತ್ತು ಸಹಚರರನ್ನು ಸೂಚಿಸುತ್ತದೆ. ನಿಮ್ಮ ಸ್ನೇಹಿತರು ನಿಜವಾದ ಮಿತ್ರರೇ ಅಥವಾ ಗುಪ್ತ ಚರಂಡಿಗಳಾ?",
        "The 2nd house and D2 chart govern accumulated treasures, gold, and grains. What is your material focus?": "2 ನೇ ಮನೆ ಮತ್ತು D2 ಚಾರ್ಟ್ ಸಂಗ್ರಹವಾದ ಸಂಪತ್ತು, ಚಿನ್ನ ಮತ್ತು ಧಾನ್ಯಗಳನ್ನು ನಿಯಂತ್ರಿಸುತ್ತದೆ. ನಿಮ್ಮ ವಸ್ತು ಗಮನ ಏನು?",
        "The 2nd house rules what enters the mouth. Diet directly shapes consciousness and physical destiny. What are you consuming?": "2 ನೇ ಮನೆಯು ಬಾಯಿಗೆ ಪ್ರವೇಶಿಸುವುದನ್ನು ನಿಯಂತ್ರಿಸುತ್ತದೆ. ಆಹಾರವು ನೇರವಾಗಿ ಪ್ರಜ್ಞೆ ಮತ್ತು ದೈಹಿಕ ಹಣೆಬರಹವನ್ನು ರೂಪಿಸುತ್ತದೆ. ನೀವು ಏನು ಸೇವಿಸುತ್ತಿದ್ದೀರಿ?",
        "The 3rd house governs the hands; the 5th governs creative intelligence. Are you honing your innate God-given skills?": "3 ನೇ ಮನೆಯು ಕೈಗಳನ್ನು ಆಳುತ್ತದೆ; 5 ನೇ ಸೃಜನಾತ್ಮಕ ಬುದ್ಧಿಮತ್ತೆಯನ್ನು ನಿಯಂತ್ರಿಸುತ್ತದೆ. ನಿಮ್ಮ ಸಹಜವಾದ ದೇವರು ನೀಡಿದ ಕೌಶಲ್ಯಗಳನ್ನು ನೀವು ಗೌರವಿಸುತ್ತಿದ್ದೀರಾ?",
        "The 3rd house rules valor (Parakrama), siblings, and the right arm. Where is your courage directed?": "3 ನೇ ಮನೆಯು ಶೌರ್ಯ (ಪರಾಕ್ರಮ), ಒಡಹುಟ್ಟಿದವರು ಮತ್ತು ಬಲಗೈಯನ್ನು ಆಳುತ್ತದೆ. ನಿಮ್ಮ ಧೈರ್ಯ ಎಲ್ಲಿ ನಿರ್ದೇಶಿಸಲ್ಪಟ್ಟಿದೆ?",
        "The 4th house and Venus dictate your comfort in travel, ownership of vehicles, beasts of burden, and daily transport. Is your carriage secure?": "4 ನೇ ಮನೆ ಮತ್ತು ಶುಕ್ರವು ಪ್ರಯಾಣ, ವಾಹನಗಳ ಮಾಲೀಕತ್ವ, ಹೊರೆಯ ಮೃಗಗಳು ಮತ್ತು ದೈನಂದಿನ ಸಾರಿಗೆಯಲ್ಲಿ ನಿಮ್ಮ ಸೌಕರ್ಯವನ್ನು ನಿರ್ದೇಶಿಸುತ್ತದೆ. ನಿಮ್ಮ ಗಾಡಿ ಸುರಕ್ಷಿತವಾಗಿದೆಯೇ?",
        "The 4th house governs fixed assets, land, and the comfort of the home. What earthly matter arises?": "4 ನೇ ಮನೆಯು ಸ್ಥಿರ ಆಸ್ತಿಗಳು, ಭೂಮಿ ಮತ್ತು ಮನೆಯ ಸೌಕರ್ಯವನ್ನು ನಿಯಂತ್ರಿಸುತ್ತದೆ. ಯಾವ ಐಹಿಕ ವಸ್ತು ಉದ್ಭವಿಸುತ್ತದೆ?",
        "The 6th house dictates your relation to hard physical labor, servants, employees, and those lower in the social hierarchy. How do you manage the toil?": "6 ನೇ ಮನೆಯು ಕಠಿಣ ದೈಹಿಕ ಶ್ರಮ, ಸೇವಕರು, ಉದ್ಯೋಗಿಗಳು ಮತ್ತು ಸಾಮಾಜಿಕ ಶ್ರೇಣಿಯಲ್ಲಿ ಕೆಳಗಿರುವವರಿಗೆ ನಿಮ್ಮ ಸಂಬಂಧವನ್ನು ನಿರ್ದೇಶಿಸುತ್ತದೆ. ನೀವು ಶ್ರಮವನ್ನು ಹೇಗೆ ನಿರ್ವಹಿಸುತ್ತೀರಿ?",
        "The 6th house governs open enemies, disputes, and royal punishments. What conflict plagues you?": "6 ನೇ ಮನೆಯು ತೆರೆದ ಶತ್ರುಗಳು, ವಿವಾದಗಳು ಮತ್ತು ರಾಜ ಶಿಕ್ಷೆಗಳನ್ನು ನಿಯಂತ್ರಿಸುತ್ತದೆ. ಯಾವ ಸಂಘರ್ಷವು ನಿಮ್ಮನ್ನು ಕಾಡುತ್ತಿದೆ?",
        "The 6th house requires the rhythmic discipline of daily life to suppress diseases and enemies. What needs correction?": "6 ನೇ ಮನೆಗೆ ರೋಗಗಳು ಮತ್ತು ಶತ್ರುಗಳನ್ನು ನಿಗ್ರಹಿಸಲು ದೈನಂದಿನ ಜೀವನದ ಲಯಬದ್ಧ ಶಿಸ್ತು ಅಗತ್ಯವಿರುತ್ತದೆ. ಏನು ತಿದ್ದುಪಡಿ ಬೇಕು?",
        "The 6th house rules Shadripu (the six enemies of the mind). Kama, Krodha, Lobha, Moha, Mada, Matsarya. Which vice has taken the reins?": "6 ನೇ ಮನೆಯು ಷಡ್ರಿಪುವನ್ನು (ಮನಸ್ಸಿನ ಆರು ಶತ್ರುಗಳು) ಆಳುತ್ತದೆ. ಕಾಮ, ಕ್ರೋಧ, ಲೋಭ, ಮೋಹ, ಮದ, ಮಾತ್ಸರ್ಯ. ಯಾವ ಉಪನಾಯಕ ಅಧಿಕಾರ ವಹಿಸಿಕೊಂಡಿದೆ?",
        "The 6th house tracks the heavy karmic chains of Runa (Debt). Are you bound to creditors, or are others bound to you?": "6 ನೇ ಮನೆಯು ರುನಾದ (ಸಾಲ) ಭಾರೀ ಕರ್ಮದ ಸರಪಳಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡುತ್ತದೆ. ನೀವು ಸಾಲಗಾರರಿಗೆ ಬದ್ಧರಾಗಿದ್ದೀರಾ ಅಥವಾ ಇತರರು ನಿಮಗೆ ಬದ್ಧರಾಗಿದ್ದೀರಾ?",
        "The 8th house and D8 chart govern Tantra, hidden dimension, and the manipulation of occult energies. Do you dare look?": "8 ನೇ ಮನೆ ಮತ್ತು D8 ಚಾರ್ಟ್ ತಂತ್ರ, ಗುಪ್ತ ಆಯಾಮ ಮತ್ತು ನಿಗೂಢ ಶಕ್ತಿಗಳ ಕುಶಲತೆಯನ್ನು ನಿಯಂತ್ರಿಸುತ್ತದೆ. ನೀವು ನೋಡಲು ಧೈರ್ಯ ಮಾಡುತ್ತೀರಾ?",
        "The 8th house rules unearned wealth, buried treasures, and sudden reversals. What hidden matter stirs?": "8 ನೇ ಮನೆಯು ಗಳಿಸದ ಸಂಪತ್ತು, ಸಮಾಧಿ ಸಂಪತ್ತು ಮತ್ತು ಹಠಾತ್ ಹಿಮ್ಮುಖವನ್ನು ನಿಯಂತ್ರಿಸುತ್ತದೆ. ಯಾವ ಗುಪ್ತ ವಿಷಯವು ಪ್ರಚೋದಿಸುತ್ತದೆ?",
        "The 9th house connects you to the deep, unshakable roots of your ancestors, language, and cultural rituals. Are you tethered or drifting?": "9 ನೇ ಮನೆಯು ನಿಮ್ಮ ಪೂರ್ವಜರು, ಭಾಷೆ ಮತ್ತು ಸಾಂಸ್ಕೃತಿಕ ಆಚರಣೆಗಳ ಆಳವಾದ, ಅಚಲವಾದ ಬೇರುಗಳಿಗೆ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತದೆ. ನೀವು ಟೆಥರ್ಡ್ ಅಥವಾ ಡ್ರಿಫ್ಟಿಂಗ್?",
        "The Arudha Lagna dictates the Maya—how the world perceives your status and renown. What is your public aim?": "ಆರೂಢ ಲಗ್ನವು ಮಾಯೆಯನ್ನು ನಿರ್ದೇಶಿಸುತ್ತದೆ - ಪ್ರಪಂಚವು ನಿಮ್ಮ ಸ್ಥಾನಮಾನ ಮತ್ತು ಖ್ಯಾತಿಯನ್ನು ಹೇಗೆ ಗ್ರಹಿಸುತ್ತದೆ. ನಿಮ್ಮ ಸಾರ್ವಜನಿಕ ಗುರಿ ಏನು?",
        "The D12 chart reveals the absolute karmic ties to the mother and father. What is the inquiry?": "D12 ಚಾರ್ಟ್ ತಾಯಿ ಮತ್ತು ತಂದೆಗೆ ಸಂಪೂರ್ಣ ಕರ್ಮ ಸಂಬಂಧಗಳನ್ನು ಬಹಿರಂಗಪಡಿಸುತ್ತದೆ. ವಿಚಾರಣೆ ಏನು?",
        "The D20 charts your spiritual receptivity and readiness for Mantra Diksha. Are you prepared to receive?": "D20 ನಿಮ್ಮ ಆಧ್ಯಾತ್ಮಿಕ ಗ್ರಹಿಕೆ ಮತ್ತು ಮಂತ್ರ ದೀಕ್ಷೆಯ ಸಿದ್ಧತೆಯನ್ನು ಪಟ್ಟಿ ಮಾಡುತ್ತದೆ. ನೀವು ಸ್ವೀಕರಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?",
        "The D6 map exposes imbalances in the Vata, Pitta, and Kapha doshas. What anomaly requires attention?": "D6 ನಕ್ಷೆಯು ವಾತ, ಪಿತ್ತ ಮತ್ತು ಕಫ ದೋಷಗಳಲ್ಲಿನ ಅಸಮತೋಲನವನ್ನು ಬಹಿರಂಗಪಡಿಸುತ್ತದೆ. ಯಾವ ಅಸಂಗತತೆಗೆ ಗಮನ ಬೇಕು?",
        "The Maraka (Death-inflicting) houses command periods of immense physical danger. Scan for immediate threats.": "ಮಾರಕಾ (ಸಾವು-ಉಂಟುಮಾಡುವ) ಮನೆಗಳು ಅಪಾರ ದೈಹಿಕ ಅಪಾಯದ ಅವಧಿಗಳನ್ನು ಆದೇಶಿಸುತ್ತವೆ. ತಕ್ಷಣದ ಬೆದರಿಕೆಗಳಿಗಾಗಿ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ.",
        "The expansion of the bloodline is governed by the 5th house. What concerns the legacy of your lineage?": "ರಕ್ತನಾಳದ ವಿಸ್ತರಣೆಯು 5 ನೇ ಮನೆಯಿಂದ ನಿಯಂತ್ರಿಸಲ್ಪಡುತ್ತದೆ. ನಿಮ್ಮ ವಂಶಾವಳಿಯ ಪರಂಪರೆಗೆ ಏನು ಸಂಬಂಧಿಸಿದೆ?",
        "The foundation of life rests upon Righteousness (Dharma). Which aspect of duty seeks clarity?": "ಜೀವನದ ಅಡಿಪಾಯವು ಸದಾಚಾರದ ಮೇಲೆ ನಿಂತಿದೆ (ಧರ್ಮ). ಕರ್ತವ್ಯದ ಯಾವ ಅಂಶವು ಸ್ಪಷ್ಟತೆಯನ್ನು ಬಯಸುತ್ತದೆ?",
        "The management of beasts, pets, and agricultural livestock falls under the 6th house. How is your relationship with the silent beings?": "ಮೃಗಗಳು, ಸಾಕುಪ್ರಾಣಿಗಳು ಮತ್ತು ಕೃಷಿ ಜಾನುವಾರುಗಳ ನಿರ್ವಹಣೆ 6 ನೇ ಮನೆಯ ಅಡಿಯಲ್ಲಿ ಬರುತ್ತದೆ. ಮೂಕ ಜೀವಿಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಸಂಬಂಧ ಹೇಗಿದೆ?",
        "The pursuit of Vidya removes darkness. What intellectual or spiritual knowledge do you seek?": "ವಿದ್ಯೆಯ ಅನ್ವೇಷಣೆಯು ಅಂಧಕಾರವನ್ನು ಹೋಗಲಾಡಿಸುತ್ತದೆ. ನೀವು ಯಾವ ಬೌದ್ಧಿಕ ಅಥವಾ ಆಧ್ಯಾತ್ಮಿಕ ಜ್ಞಾನವನ್ನು ಬಯಸುತ್ತೀರಿ?",
        "The sacred union of Vivaha binds two souls karmically. What is your inquiry regarding marital bonds?": "ವಿವಾಹದ ಪವಿತ್ರ ಒಕ್ಕೂಟವು ಎರಡು ಆತ್ಮಗಳನ್ನು ಕರ್ಮವಾಗಿ ಬಂಧಿಸುತ್ತದೆ. ವೈವಾಹಿಕ ಬಂಧಗಳಿಗೆ ಸಂಬಂಧಿಸಿದಂತೆ ನಿಮ್ಮ ವಿಚಾರಣೆ ಏನು?",
        "The subconscious mind receives signals from the astral plane. What omens are manifesting?": "ಉಪಪ್ರಜ್ಞೆ ಮನಸ್ಸು ಆಸ್ಟ್ರಲ್ ಪ್ಲೇನ್‌ನಿಂದ ಸಂಕೇತಗಳನ್ನು ಪಡೆಯುತ್ತದೆ. ಯಾವ ಶಕುನಗಳು ಪ್ರಕಟವಾಗುತ್ತವೆ?",
        "The ultimate aim is liberation from the cycle of birth and death. What blocks your spiritual ascent?": "ಜನನ ಮತ್ತು ಮರಣದ ಚಕ್ರದಿಂದ ಮುಕ್ತಿಯೇ ಅಂತಿಮ ಗುರಿಯಾಗಿದೆ. ನಿಮ್ಮ ಆಧ್ಯಾತ್ಮಿಕ ಆರೋಹಣವನ್ನು ಯಾವುದು ನಿರ್ಬಂಧಿಸುತ್ತದೆ?",
        "Travel for spiritual merit or foreign expansion requires alignment. What is the nature of the journey?": "ಆಧ್ಯಾತ್ಮಿಕ ಅರ್ಹತೆ ಅಥವಾ ವಿದೇಶಿ ವಿಸ್ತರಣೆಗಾಗಿ ಪ್ರಯಾಣಕ್ಕೆ ಹೊಂದಾಣಿಕೆಯ ಅಗತ್ಯವಿದೆ. ಪ್ರಯಾಣದ ಸ್ವರೂಪವೇನು?",
        "True wealth is internal peace (Sukha) and a harmonious home. What disturbs the waters of the mind?": "ನಿಜವಾದ ಸಂಪತ್ತು ಆಂತರಿಕ ಶಾಂತಿ (ಸುಖ) ಮತ್ತು ಸಾಮರಸ್ಯದ ಮನೆಯಾಗಿದೆ. ಮನಸ್ಸಿನ ನೀರನ್ನು ಯಾವುದು ಕದಡುತ್ತದೆ?",
        "We carry the unsolved debts of our forefathers. What ancestral affliction requires propitiation?": "ನಮ್ಮ ಪೂರ್ವಜರ ತೀರಿಸಲಾಗದ ಸಾಲವನ್ನು ನಾವು ಹೊತ್ತಿದ್ದೇವೆ. ಯಾವ ಪೂರ್ವಜರ ಸಂಕಟಕ್ಕೆ ಪ್ರಾಯಶ್ಚಿತ್ತದ ಅಗತ್ಯವಿದೆ?",
        "Wealth that is hoarded rots the soul. Danam (Charity) is the great purifier of the D2 treasury. Where must your resources flow?": "ಸಂಗ್ರಹಿಸಿದ ಸಂಪತ್ತು ಆತ್ಮವನ್ನು ಕೊಳೆಯುತ್ತದೆ. ದಾನಮ್ (ದಾನ) D2 ಖಜಾನೆಯ ಮಹಾನ್ ಶುದ್ಧಿಕಾರಕವಾಗಿದೆ. ನಿಮ್ಮ ಸಂಪನ್ಮೂಲಗಳು ಎಲ್ಲಿ ಹರಿಯಬೇಕು?"
    },
    "te": {
        "10th House Karma": "10వ గృహ కర్మ",
        "11th House Bonds": "11వ గృహ బంధాలు",
        "11th House Gains": "11వ గృహ లాభాలు",
        "12th/5th House Release": "12వ/5వ హౌస్ విడుదల",
        "12th/9th House Vectors": "12వ/9వ హౌస్ వెక్టర్స్",
        "2nd House Sustenance": "2వ ఇంటి జీవనోపాధి",
        "3rd/5th House Skills": "3వ/5వ ఇంటి నైపుణ్యాలు",
        "4th House Mobility": "4వ హౌస్ మొబిలిటీ",
        "4th House Tranquility": "4వ ఇంటి ప్రశాంతత",
        "6th House Afflictions": "6వ ఇంటి బాధలు",
        "6th House Companions": "6వ ఇంటి సహచరులు",
        "6th House Discipline": "6వ ఇంటి క్రమశిక్షణ",
        "6th House Ledgers": "6వ హౌస్ లెడ్జర్స్",
        "6th/Saturn Karma": "6వ/శని కర్మ",
        "8th House Mysteries": "8వ ఇంటి రహస్యాలు",
        "9th House Philanthropy": "9వ ఇల్లు దాతృత్వం",
        "9th House Roots": "9 వ ఇంటి మూలాలు",
        "Afflictions demand propitiation. Which traditional remedial measure do you seek to enact?": "బాధలు ప్రాయశ్చిత్తాన్ని కోరుతాయి. మీరు ఏ సాంప్రదాయ నివారణ చర్యను అమలు చేయాలనుకుంటున్నారు?",
        "Arudha Lagna Profile": "ఆరూఢ లగ్న ప్రొఫైల్",
        "Between the grinding gears of Dharma and Artha, the soul requires Vishrama (rest) and playful release to maintain sanity. How do you retreat?": "ధర్మం మరియు అర్థాల గ్రైండింగ్ గేర్‌ల మధ్య, ఆత్మకు చిత్తశుద్ధిని కాపాడుకోవడానికి విశ్రమ (విశ్రాంతి) మరియు ఉల్లాసభరితమైన విడుదల అవసరం. మీరు ఎలా వెనక్కి తగ్గుతారు?",
        "D12 Dwadasamsa": "D12 ద్వాదశాంశ",
        "D2 Hora Liquidity": "D2 హోరా లిక్విడిటీ",
        "D20 Vimsamsa": "D20 Vimsamsa",
        "D24 Chaturvimsamsa": "D24 చతుర్వింశంస",
        "D3 Drekkana": "D3 డ్రెక్కనా",
        "D30 Trimsamsa": "D30 త్రిమ్సంస",
        "D4 Chaturthamsa": "D4 చతుర్థాంశ",
        "D40 Khavedamsa": "D40 ఖవేదంస",
        "D6 Bodily Humors": "D6 శారీరక హాస్యం",
        "D60 Shashtiamsa": "D60 షష్ఠిాంశ",
        "D7 Saptamsa Matrix": "D7 సప్తాంశ మాతృక",
        "D8 Ashtamsa Matrix": "D8 అష్టాంశ మాతృక",
        "D9 & 9th House Rectitude": "D9 & 9వ హౌస్ రెక్టిట్యూడ్",
        "D9 Navamsa Harmony": "D9 నవాంశ సామరస్యం",
        "Dosha Mitigation": "దోష నివారణ",
        "Maraka & Badhaka": "మారకా & బాధకా",
        "Muhurta aligns human action with divine time. What auspicious event are you planning?": "ముహూర్తం మానవ చర్యను దైవిక సమయంతో సమలేఖనం చేస్తుంది. మీరు ఏ శుభ కార్యక్రమం ప్లాన్ చేస్తున్నారు?",
        "Panchanga Engine": "పంచాంగ ఇంజిన్",
        "Swapna Shastra": "స్వప్న శాస్త్రం",
        "The 10th house governs your livelihood, daily trade, and standing before employers. What is the state of your work?": "10వ ఇల్లు మీ జీవనోపాధిని, రోజువారీ వ్యాపారాన్ని మరియు యజమానుల ముందు నిలబడడాన్ని నియంత్రిస్తుంది. మీ పని పరిస్థితి ఏమిటి?",
        "The 11th house dictates your ability to extract wealth and favors from large societies or guilds. What is the objective?": "11వ ఇల్లు పెద్ద సమాజాలు లేదా గిల్డ్‌ల నుండి సంపద మరియు సహాయాలను సేకరించే మీ సామర్థ్యాన్ని నిర్దేశిస్తుంది. లక్ష్యం ఏమిటి?",
        "The 11th house signifies the networks and companions we choose. Are your friends true allies or hidden drains?": "11వ ఇల్లు మనం ఎంచుకున్న నెట్‌వర్క్‌లు మరియు సహచరులను సూచిస్తుంది. మీ స్నేహితులు నిజమైన మిత్రులా లేక దాచిన కాలువలా?",
        "The 2nd house and D2 chart govern accumulated treasures, gold, and grains. What is your material focus?": "2వ ఇల్లు మరియు D2 చార్ట్ సేకరించబడిన నిధులు, బంగారం మరియు ధాన్యాలను నియంత్రిస్తుంది. మీ మెటీరియల్ ఫోకస్ ఏమిటి?",
        "The 2nd house rules what enters the mouth. Diet directly shapes consciousness and physical destiny. What are you consuming?": "2 వ ఇల్లు నోటిలోకి ప్రవేశించే వాటిని నియమిస్తుంది. ఆహారం నేరుగా స్పృహ మరియు భౌతిక విధిని రూపొందిస్తుంది. మీరు ఏమి వినియోగిస్తున్నారు?",
        "The 3rd house governs the hands; the 5th governs creative intelligence. Are you honing your innate God-given skills?": "3 వ ఇల్లు చేతులను నియంత్రిస్తుంది; 5 వ సృజనాత్మక మేధస్సును నియంత్రిస్తుంది. మీరు మీ సహజసిద్ధమైన దేవుడు ఇచ్చిన నైపుణ్యాలను మెరుగుపరుచుకుంటున్నారా?",
        "The 3rd house rules valor (Parakrama), siblings, and the right arm. Where is your courage directed?": "3వ ఇల్లు శౌర్యాన్ని (పరాక్రమ), తోబుట్టువులు మరియు కుడి భుజాన్ని నియమిస్తుంది. నీ ధైర్యం ఎక్కడికి దారి తీసింది?",
        "The 4th house and Venus dictate your comfort in travel, ownership of vehicles, beasts of burden, and daily transport. Is your carriage secure?": "4వ ఇల్లు మరియు శుక్రుడు ప్రయాణాలలో మీ సౌకర్యాన్ని, వాహనాల యాజమాన్యాన్ని, భారమైన మృగాలను మరియు రోజువారీ రవాణాను నిర్దేశిస్తారు. మీ క్యారేజ్ సురక్షితంగా ఉందా?",
        "The 4th house governs fixed assets, land, and the comfort of the home. What earthly matter arises?": "4వ ఇల్లు స్థిర ఆస్తులు, భూమి మరియు ఇంటి సౌకర్యాన్ని నియంత్రిస్తుంది. ఏ భూసంబంధమైన పదార్థం పుడుతుంది?",
        "The 6th house dictates your relation to hard physical labor, servants, employees, and those lower in the social hierarchy. How do you manage the toil?": "6వ ఇల్లు కఠినమైన శారీరక శ్రమ, సేవకులు, ఉద్యోగులు మరియు సామాజిక సోపానక్రమంలో తక్కువ వారితో మీ సంబంధాన్ని నిర్దేశిస్తుంది. మీరు శ్రమను ఎలా నిర్వహిస్తారు?",
        "The 6th house governs open enemies, disputes, and royal punishments. What conflict plagues you?": "6 వ ఇల్లు బహిరంగ శత్రువులు, వివాదాలు మరియు రాజ శిక్షలను నియంత్రిస్తుంది. ఏ సంఘర్షణ మిమ్మల్ని వేధిస్తోంది?",
        "The 6th house requires the rhythmic discipline of daily life to suppress diseases and enemies. What needs correction?": "6 వ ఇంటికి వ్యాధులు మరియు శత్రువులను అణచివేయడానికి రోజువారీ జీవితంలో లయబద్ధమైన క్రమశిక్షణ అవసరం. దిద్దుబాటు అవసరం ఏమిటి?",
        "The 6th house rules Shadripu (the six enemies of the mind). Kama, Krodha, Lobha, Moha, Mada, Matsarya. Which vice has taken the reins?": "6వ ఇల్లు షడ్రిపుని (మనస్సుకు ఆరుగురు శత్రువులు) పాలిస్తుంది. కామ, క్రోధ, లోభ, మోహ, మద, మాత్సర్య. ఏ వైస్ పగ్గాలు చేపట్టింది?",
        "The 6th house tracks the heavy karmic chains of Runa (Debt). Are you bound to creditors, or are others bound to you?": "6వ ఇల్లు రూనా (అప్పు) యొక్క భారీ కర్మ గొలుసులను ట్రాక్ చేస్తుంది. మీరు రుణదాతలకు కట్టుబడి ఉన్నారా లేదా ఇతరులు మీకు కట్టుబడి ఉన్నారా?",
        "The 8th house and D8 chart govern Tantra, hidden dimension, and the manipulation of occult energies. Do you dare look?": "8వ ఇల్లు మరియు D8 చార్ట్ తంత్రం, దాచిన పరిమాణం మరియు క్షుద్ర శక్తుల తారుమారుని నియంత్రిస్తాయి. చూసే ధైర్యం ఉందా?",
        "The 8th house rules unearned wealth, buried treasures, and sudden reversals. What hidden matter stirs?": "8వ ఇల్లు సంపాదించని సంపద, ఖననం చేయబడిన సంపద మరియు ఆకస్మిక తిరోగమనాలను నియమిస్తుంది. ఏ దాచిన విషయం కదిలిస్తుంది?",
        "The 9th house connects you to the deep, unshakable roots of your ancestors, language, and cultural rituals. Are you tethered or drifting?": "9వ ఇల్లు మీ పూర్వీకులు, భాష మరియు సాంస్కృతిక ఆచారాల యొక్క లోతైన, అస్థిరమైన మూలాలకు మిమ్మల్ని కలుపుతుంది. మీరు ముడిపడి ఉన్నారా లేదా డ్రిఫ్టింగ్ చేస్తున్నారా?",
        "The Arudha Lagna dictates the Maya—how the world perceives your status and renown. What is your public aim?": "ఆరూఢ లగ్న మాయను నిర్దేశిస్తుంది - ప్రపంచం మీ స్థితిని మరియు కీర్తిని ఎలా గ్రహిస్తుంది. మీ ప్రజా లక్ష్యం ఏమిటి?",
        "The D12 chart reveals the absolute karmic ties to the mother and father. What is the inquiry?": "D12 చార్ట్ తల్లి మరియు తండ్రికి సంపూర్ణ కర్మ సంబంధాలను వెల్లడిస్తుంది. విచారణ ఏమిటి?",
        "The D20 charts your spiritual receptivity and readiness for Mantra Diksha. Are you prepared to receive?": "మంత్ర దీక్ష కోసం మీ ఆధ్యాత్మిక గ్రహణశక్తి మరియు సంసిద్ధతను D20 చార్ట్ చేస్తుంది. మీరు స్వీకరించడానికి సిద్ధంగా ఉన్నారా?",
        "The D6 map exposes imbalances in the Vata, Pitta, and Kapha doshas. What anomaly requires attention?": "D6 మ్యాప్ వాత, పిత్త మరియు కఫ దోషాలలో అసమతుల్యతను బహిర్గతం చేస్తుంది. ఏ క్రమరాహిత్యానికి శ్రద్ధ అవసరం?",
        "The Maraka (Death-inflicting) houses command periods of immense physical danger. Scan for immediate threats.": "మరకా (మరణాన్ని కలిగించే) గృహాలు అపారమైన భౌతిక ప్రమాదాన్ని కలిగి ఉంటాయి. తక్షణ బెదిరింపుల కోసం స్కాన్ చేయండి.",
        "The expansion of the bloodline is governed by the 5th house. What concerns the legacy of your lineage?": "రక్తసంబంధం యొక్క విస్తరణ 5 వ ఇంటిచే నిర్వహించబడుతుంది. మీ వంశ వారసత్వానికి సంబంధించినది ఏమిటి?",
        "The foundation of life rests upon Righteousness (Dharma). Which aspect of duty seeks clarity?": "జీవితానికి పునాది ధర్మం (ధర్మం)పై ఆధారపడి ఉంటుంది. విధి యొక్క ఏ అంశం స్పష్టతను కోరుతుంది?",
        "The management of beasts, pets, and agricultural livestock falls under the 6th house. How is your relationship with the silent beings?": "జంతువులు, పెంపుడు జంతువులు మరియు వ్యవసాయ పశువుల నిర్వహణ 6వ ఇంటి క్రిందకు వస్తుంది. నిశ్శబ్ద జీవులతో మీ సంబంధం ఎలా ఉంది?",
        "The pursuit of Vidya removes darkness. What intellectual or spiritual knowledge do you seek?": "విద్య సాధన చీకటిని తొలగిస్తుంది. మీరు ఏ మేధో లేదా ఆధ్యాత్మిక జ్ఞానాన్ని కోరుకుంటారు?",
        "The sacred union of Vivaha binds two souls karmically. What is your inquiry regarding marital bonds?": "వివాహ యొక్క పవిత్ర కలయిక రెండు ఆత్మలను కర్మగా బంధిస్తుంది. వివాహ బంధాలకు సంబంధించి మీ విచారణ ఏమిటి?",
        "The subconscious mind receives signals from the astral plane. What omens are manifesting?": "ఉపచేతన మనస్సు జ్యోతిష్య విమానం నుండి సంకేతాలను అందుకుంటుంది. ఏ శకునాలు వ్యక్తమవుతున్నాయి?",
        "The ultimate aim is liberation from the cycle of birth and death. What blocks your spiritual ascent?": "జనన మరణ చక్రం నుండి విముక్తి పొందడమే అంతిమ లక్ష్యం. మీ ఆధ్యాత్మిక ఆరోహణను ఏది అడ్డుకుంటుంది?",
        "Travel for spiritual merit or foreign expansion requires alignment. What is the nature of the journey?": "ఆధ్యాత్మిక యోగ్యత లేదా విదేశీ విస్తరణ కోసం ప్రయాణానికి సమలేఖనం అవసరం. ప్రయాణం యొక్క స్వభావం ఏమిటి?",
        "True wealth is internal peace (Sukha) and a harmonious home. What disturbs the waters of the mind?": "నిజమైన సంపద అంతర్గత శాంతి (సుఖ) మరియు సామరస్య గృహం. మనసులోని నీటిని కలవరపెట్టేది ఏమిటి?",
        "We carry the unsolved debts of our forefathers. What ancestral affliction requires propitiation?": "మా పూర్వీకుల తీర్చని అప్పులను మేము మోస్తున్నాము. ఏ పూర్వీకుల బాధలకు ప్రాయశ్చిత్తం అవసరం?",
        "Wealth that is hoarded rots the soul. Danam (Charity) is the great purifier of the D2 treasury. Where must your resources flow?": "కూడబెట్టిన సంపద ఆత్మను కుళ్ళిస్తుంది. దానం (ధార్మికత) అనేది D2 ఖజానా యొక్క గొప్ప శుద్ధి. మీ వనరులు ఎక్కడ ప్రవహించాలి?"
    },
    "ta": {
        "10th House Karma": "10 வது வீடு கர்மா",
        "11th House Bonds": "11வது வீட்டுப் பத்திரங்கள்",
        "11th House Gains": "11ம் வீடு லாபம்",
        "12th/5th House Release": "12வது/5வது வீடு வெளியீடு",
        "12th/9th House Vectors": "12வது/9வது வீட்டின் திசையன்கள்",
        "2nd House Sustenance": "2 வது வீட்டு உணவு",
        "3rd/5th House Skills": "3வது/5வது வீட்டுத் திறன்கள்",
        "4th House Mobility": "4 வது வீட்டின் இயக்கம்",
        "4th House Tranquility": "4 வது வீட்டின் அமைதி",
        "6th House Afflictions": "6 வது வீட்டின் துன்பங்கள்",
        "6th House Companions": "6 வது வீட்டு தோழர்கள்",
        "6th House Discipline": "6 வது வீட்டு ஒழுக்கம்",
        "6th House Ledgers": "6 வது ஹவுஸ் லெட்ஜர்கள்",
        "6th/Saturn Karma": "6ல்/சனி கர்மா",
        "8th House Mysteries": "8 வது வீட்டின் மர்மங்கள்",
        "9th House Philanthropy": "9 வது வீடு பரோபகாரம்",
        "9th House Roots": "9 வது வீட்டின் வேர்கள்",
        "Afflictions demand propitiation. Which traditional remedial measure do you seek to enact?": "துன்பங்கள் சாந்தத்தைக் கோருகின்றன. எந்த பாரம்பரிய தீர்வு நடவடிக்கையை நீங்கள் இயற்ற விரும்புகிறீர்கள்?",
        "Arudha Lagna Profile": "ஆருட லக்ன விவரம்",
        "Between the grinding gears of Dharma and Artha, the soul requires Vishrama (rest) and playful release to maintain sanity. How do you retreat?": "தர்மம் மற்றும் அர்த்தத்தின் அரைக்கும் கியர்களுக்கு இடையில், ஆன்மாவுக்கு விஷ்ரம் (ஓய்வு) மற்றும் நல்லிணக்கத்தை பராமரிக்க விளையாட்டுத்தனமான விடுதலை தேவைப்படுகிறது. நீங்கள் எப்படி பின்வாங்குகிறீர்கள்?",
        "D12 Dwadasamsa": "D12 த்வாதசாம்சம்",
        "D2 Hora Liquidity": "D2 ஹோரா திரவத்தன்மை",
        "D20 Vimsamsa": "டி20 விம்சம்சா",
        "D24 Chaturvimsamsa": "D24 சதுர்விம்சம்சா",
        "D3 Drekkana": "டி3 டிரேக்கனா",
        "D30 Trimsamsa": "டி30 த்ரிம்சம்சா",
        "D4 Chaturthamsa": "D4 சதுர்தாம்சம்",
        "D40 Khavedamsa": "டி40 கவேதம்சா",
        "D6 Bodily Humors": "D6 உடல் நகைச்சுவை",
        "D60 Shashtiamsa": "டி60 ஷஷ்டியாம்சா",
        "D7 Saptamsa Matrix": "டி7 சப்தம்சா மேட்ரிக்ஸ்",
        "D8 Ashtamsa Matrix": "D8 அஷ்டம்சா அணி",
        "D9 & 9th House Rectitude": "D9 & 9 வது வீட்டின் நேர்கோட்டு",
        "D9 Navamsa Harmony": "D9 நவாம்ச ஹார்மனி",
        "Dosha Mitigation": "தோஷ தணிப்பு",
        "Maraka & Badhaka": "மரக்கா & பாதகா",
        "Muhurta aligns human action with divine time. What auspicious event are you planning?": "முஹூர்த்தா மனித செயலை தெய்வீக நேரத்துடன் சீரமைக்கிறது. நீங்கள் என்ன சுப நிகழ்ச்சியை திட்டமிடுகிறீர்கள்?",
        "Panchanga Engine": "பஞ்சாங்க எஞ்சின்",
        "Swapna Shastra": "ஸ்வப்னா சாஸ்திரம்",
        "The 10th house governs your livelihood, daily trade, and standing before employers. What is the state of your work?": "10வது வீடு உங்கள் வாழ்வாதாரம், தினசரி வர்த்தகம் மற்றும் முதலாளிகளின் முன் நிற்கிறது. உங்கள் பணியின் நிலை என்ன?",
        "The 11th house dictates your ability to extract wealth and favors from large societies or guilds. What is the objective?": "11 வது வீடு பெரிய சமூகங்கள் அல்லது கில்டுகளிடமிருந்து செல்வத்தையும் ஆதரவையும் பெறுவதற்கான உங்கள் திறனைக் கட்டளையிடுகிறது. குறிக்கோள் என்ன?",
        "The 11th house signifies the networks and companions we choose. Are your friends true allies or hidden drains?": "11 வது வீடு நாம் தேர்ந்தெடுக்கும் நெட்வொர்க்குகள் மற்றும் தோழர்களைக் குறிக்கிறது. உங்கள் நண்பர்கள் உண்மையான கூட்டாளிகளா அல்லது மறைக்கப்பட்ட வடிகால்களா?",
        "The 2nd house and D2 chart govern accumulated treasures, gold, and grains. What is your material focus?": "2 வது வீடு மற்றும் D2 விளக்கப்படம் குவிக்கப்பட்ட பொக்கிஷங்கள், தங்கம் மற்றும் தானியங்களை நிர்வகிக்கிறது. உங்கள் பொருள் கவனம் என்ன?",
        "The 2nd house rules what enters the mouth. Diet directly shapes consciousness and physical destiny. What are you consuming?": "2வது வீடு வாயில் நுழைவதை ஆளுகிறது. உணவு நேரடியாக உணர்வு மற்றும் உடல் விதியை வடிவமைக்கிறது. நீங்கள் என்ன சாப்பிடுகிறீர்கள்?",
        "The 3rd house governs the hands; the 5th governs creative intelligence. Are you honing your innate God-given skills?": "3வது வீடு கைகளை ஆளுகிறது; 5வது படைப்பு நுண்ணறிவைக் கட்டுப்படுத்துகிறது. கடவுள் கொடுத்த உங்கள் உள்ளார்ந்த திறமைகளை நீங்கள் மெருகேற்றுகிறீர்களா?",
        "The 3rd house rules valor (Parakrama), siblings, and the right arm. Where is your courage directed?": "3 ஆம் வீடு வீரம் (பராக்கிரமம்), உடன்பிறந்தவர்கள் மற்றும் வலது கையை ஆளுகிறது. உங்கள் தைரியம் எங்கே செல்கிறது?",
        "The 4th house and Venus dictate your comfort in travel, ownership of vehicles, beasts of burden, and daily transport. Is your carriage secure?": "நான்காம் வீடு மற்றும் சுக்கிரன் பயணம், வாகனங்களின் உரிமை, சுமை மிருகங்கள் மற்றும் தினசரி போக்குவரத்து ஆகியவற்றில் உங்கள் வசதியை ஆணையிடுகிறது. உங்கள் வண்டி பாதுகாப்பானதா?",
        "The 4th house governs fixed assets, land, and the comfort of the home. What earthly matter arises?": "4 வது வீடு நிலையான சொத்துக்கள், நிலம் மற்றும் வீட்டின் வசதியை நிர்வகிக்கிறது. என்ன பூமிக்குரிய விஷயம் எழுகிறது?",
        "The 6th house dictates your relation to hard physical labor, servants, employees, and those lower in the social hierarchy. How do you manage the toil?": "6 வது வீடு கடினமான உடல் உழைப்பு, வேலையாட்கள், பணியாளர்கள் மற்றும் சமூக வரிசைக்கு கீழ் உள்ளவர்களுடன் உங்கள் உறவை ஆணையிடுகிறது. உழைப்பை எப்படி நிர்வகிக்கிறீர்கள்?",
        "The 6th house governs open enemies, disputes, and royal punishments. What conflict plagues you?": "6 ஆம் வீடு திறந்த எதிரிகள், சச்சரவுகள் மற்றும் அரச தண்டனைகளை நிர்வகிக்கிறது. என்ன மோதல் உங்களைப் பாதிக்கிறது?",
        "The 6th house requires the rhythmic discipline of daily life to suppress diseases and enemies. What needs correction?": "6 ஆம் வீட்டிற்கு நோய்கள் மற்றும் எதிரிகளை அடக்குவதற்கு தினசரி வாழ்க்கையின் தாள ஒழுக்கம் தேவைப்படுகிறது. என்ன திருத்தம் தேவை?",
        "The 6th house rules Shadripu (the six enemies of the mind). Kama, Krodha, Lobha, Moha, Mada, Matsarya. Which vice has taken the reins?": "6வது வீடு ஷத்ரிபுவை (மனதின் ஆறு எதிரிகள்) ஆட்சி செய்கிறது. காம, க்ரோதா, லோபா, மோஹ, மத, மாத்சார்ய. எந்த துணை ஆட்சியை பிடித்தது?",
        "The 6th house tracks the heavy karmic chains of Runa (Debt). Are you bound to creditors, or are others bound to you?": "6 வது வீடு ருனாவின் (கடன்) கனமான கர்ம சங்கிலிகளைக் கண்காணிக்கிறது. நீங்கள் கடனாளிகளுக்குக் கட்டுப்படுகிறீர்களா அல்லது மற்றவர்கள் உங்களுக்குக் கட்டுப்பட்டவர்களா?",
        "The 8th house and D8 chart govern Tantra, hidden dimension, and the manipulation of occult energies. Do you dare look?": "8வது வீடு மற்றும் D8 விளக்கப்படம் தந்திரம், மறைக்கப்பட்ட பரிமாணம் மற்றும் அமானுஷ்ய ஆற்றல்களின் கையாளுதல் ஆகியவற்றை நிர்வகிக்கிறது. பார்க்க தைரியமா?",
        "The 8th house rules unearned wealth, buried treasures, and sudden reversals. What hidden matter stirs?": "எட்டாவது வீடு பெறாத செல்வம், புதைக்கப்பட்ட பொக்கிஷங்கள் மற்றும் திடீர் தலைகீழாக மாறுகிறது. என்ன மறைக்கப்பட்ட விஷயம் தூண்டுகிறது?",
        "The 9th house connects you to the deep, unshakable roots of your ancestors, language, and cultural rituals. Are you tethered or drifting?": "9 வது வீடு உங்கள் முன்னோர்கள், மொழி மற்றும் கலாச்சார சடங்குகளின் ஆழமான, அசைக்க முடியாத வேர்களுடன் உங்களை இணைக்கிறது. நீங்கள் இணைக்கப்பட்டுள்ளீர்களா அல்லது அலைந்து கொண்டிருக்கிறீர்களா?",
        "The Arudha Lagna dictates the Maya—how the world perceives your status and renown. What is your public aim?": "ஆருட லக்னம் மாயாவை ஆணையிடுகிறது - உலகம் உங்கள் நிலை மற்றும் புகழை எவ்வாறு உணர்கிறது. உங்கள் பொது நோக்கம் என்ன?",
        "The D12 chart reveals the absolute karmic ties to the mother and father. What is the inquiry?": "D12 விளக்கப்படம் தாய் மற்றும் தந்தையுடனான முழுமையான கர்ம உறவுகளை வெளிப்படுத்துகிறது. விசாரணை என்ன?",
        "The D20 charts your spiritual receptivity and readiness for Mantra Diksha. Are you prepared to receive?": "D20 உங்கள் ஆன்மீக வரவேற்பு மற்றும் மந்திர தீட்சைக்கான தயார்நிலையை விளக்குகிறது. பெற நீங்கள் தயாரா?",
        "The D6 map exposes imbalances in the Vata, Pitta, and Kapha doshas. What anomaly requires attention?": "D6 வரைபடம் வாத, பித்த மற்றும் கப தோஷங்களில் உள்ள ஏற்றத்தாழ்வுகளை வெளிப்படுத்துகிறது. என்ன ஒழுங்கின்மைக்கு கவனம் தேவை?",
        "The Maraka (Death-inflicting) houses command periods of immense physical danger. Scan for immediate threats.": "மரக்கா (மரணத்தை உண்டாக்கும்) வீடுகள் மிகப்பெரிய உடல் ஆபத்தின் காலகட்டங்களைக் கட்டளையிடுகின்றன. உடனடி அச்சுறுத்தல்களுக்கு ஸ்கேன் செய்யவும்.",
        "The expansion of the bloodline is governed by the 5th house. What concerns the legacy of your lineage?": "இரத்த ஓட்டத்தின் விரிவாக்கம் 5 வது வீட்டால் நிர்வகிக்கப்படுகிறது. உங்கள் பரம்பரை பரம்பரை பற்றி என்ன?",
        "The foundation of life rests upon Righteousness (Dharma). Which aspect of duty seeks clarity?": "வாழ்க்கையின் அடித்தளம் நீதியின் (தர்மம்) மீது தங்கியுள்ளது. கடமையின் எந்த அம்சம் தெளிவைத் தேடுகிறது?",
        "The management of beasts, pets, and agricultural livestock falls under the 6th house. How is your relationship with the silent beings?": "மிருகங்கள், செல்லப்பிராணிகள் மற்றும் விவசாய கால்நடைகளின் மேலாண்மை 6 வது வீட்டின் கீழ் வருகிறது. அமைதியான உயிரினங்களுடனான உங்கள் உறவு எப்படி இருக்கிறது?",
        "The pursuit of Vidya removes darkness. What intellectual or spiritual knowledge do you seek?": "வித்யாவின் நாட்டம் இருளை நீக்குகிறது. நீங்கள் என்ன அறிவுசார் அல்லது ஆன்மீக அறிவைத் தேடுகிறீர்கள்?",
        "The sacred union of Vivaha binds two souls karmically. What is your inquiry regarding marital bonds?": "விவாஹாவின் புனித சங்கமம் இரண்டு ஆன்மாக்களை கர்ம ரீதியாக பிணைக்கிறது. திருமணப் பத்திரங்கள் தொடர்பான உங்கள் விசாரணை என்ன?",
        "The subconscious mind receives signals from the astral plane. What omens are manifesting?": "ஆழ் மனம் நிழலிடா விமானத்திலிருந்து சமிக்ஞைகளைப் பெறுகிறது. என்ன சகுனங்கள் வெளிப்படுகின்றன?",
        "The ultimate aim is liberation from the cycle of birth and death. What blocks your spiritual ascent?": "பிறப்பு இறப்பு சுழற்சியில் இருந்து விடுதலை பெறுவதே இறுதி நோக்கம். உங்கள் ஆன்மீக ஏற்றத்தைத் தடுப்பது எது?",
        "Travel for spiritual merit or foreign expansion requires alignment. What is the nature of the journey?": "ஆன்மீக தகுதி அல்லது வெளிநாட்டு விரிவாக்கத்திற்கான பயணம் சீரமைப்பு தேவை. பயணத்தின் தன்மை என்ன?",
        "True wealth is internal peace (Sukha) and a harmonious home. What disturbs the waters of the mind?": "உண்மையான செல்வம் என்பது உள் அமைதி (சுகா) மற்றும் இணக்கமான வீடு. மனதின் நீரைக் குழப்புவது எது?",
        "We carry the unsolved debts of our forefathers. What ancestral affliction requires propitiation?": "நம் முன்னோர்களின் தீர்க்கப்படாத கடன்களை சுமக்கிறோம். எந்த மூதாதையர் துன்பங்களுக்குப் பரிகாரம் தேவை?",
        "Wealth that is hoarded rots the soul. Danam (Charity) is the great purifier of the D2 treasury. Where must your resources flow?": "பதுக்கி வைத்திருக்கும் செல்வம் உள்ளத்தை அழித்துவிடும். தனம் (தொண்டு) என்பது D2 கருவூலத்தின் சிறந்த சுத்திகரிப்பு ஆகும். உங்கள் வளங்கள் எங்கே ஓட வேண்டும்?"
    },
    "ml": {
        "10th House Karma": "10-ാം ഭവന കർമ്മം",
        "11th House Bonds": "11-ാമത്തെ ഹൗസ് ബോണ്ടുകൾ",
        "11th House Gains": "11-ാം ഭവന നേട്ടം",
        "12th/5th House Release": "12/5 ഹൗസ് റിലീസ്",
        "12th/9th House Vectors": "12/9 ഹൗസ് വെക്‌ടറുകൾ",
        "2nd House Sustenance": "രണ്ടാം ഹൗസ് ഉപജീവനം",
        "3rd/5th House Skills": "3rd/5th ഹൗസ് സ്കിൽസ്",
        "4th House Mobility": "നാലാമത്തെ ഹൗസ് മൊബിലിറ്റി",
        "4th House Tranquility": "നാലാമത്തെ വീടിൻ്റെ ശാന്തത",
        "6th House Afflictions": "6-ാം ഹൗസ് ക്ലേശങ്ങൾ",
        "6th House Companions": "ആറാമത്തെ ഹൗസ് കൂട്ടുകാർ",
        "6th House Discipline": "ആറാം ഹൗസ് അച്ചടക്കം",
        "6th House Ledgers": "ആറാമത്തെ ഹൗസ് ലെഡ്ജറുകൾ",
        "6th/Saturn Karma": "6/ശനി കർമ്മം",
        "8th House Mysteries": "എട്ടാമത്തെ വീടിൻ്റെ രഹസ്യങ്ങൾ",
        "9th House Philanthropy": "9-ാം ഭവനം ജീവകാരുണ്യപ്രവർത്തനം",
        "9th House Roots": "9 ഹൗസ് വേരുകൾ",
        "Afflictions demand propitiation. Which traditional remedial measure do you seek to enact?": "ക്ലേശങ്ങൾ പാപപരിഹാരം ആവശ്യപ്പെടുന്നു. ഏത് പരമ്പരാഗത പരിഹാര നടപടിയാണ് നിങ്ങൾ നടപ്പിലാക്കാൻ ശ്രമിക്കുന്നത്?",
        "Arudha Lagna Profile": "ആരൂഢ ലഗ്ന പ്രൊഫൈൽ",
        "Between the grinding gears of Dharma and Artha, the soul requires Vishrama (rest) and playful release to maintain sanity. How do you retreat?": "ധർമ്മത്തിൻ്റെയും അർത്ഥത്തിൻ്റെയും ഉരച്ചിലുകൾക്കിടയിൽ, ആത്മാവിന് വിവേകം നിലനിർത്താൻ വിശ്രമവും (വിശ്രമവും) കളിയായ മോചനവും ആവശ്യമാണ്. നിങ്ങൾ എങ്ങനെയാണ് പിൻവാങ്ങുന്നത്?",
        "D12 Dwadasamsa": "D12 ദ്വാദശാംസം",
        "D2 Hora Liquidity": "D2 ഹോറ ലിക്വിഡിറ്റി",
        "D20 Vimsamsa": "D20 Vimsamsa",
        "D24 Chaturvimsamsa": "D24 ചതുർവിംശംസ",
        "D3 Drekkana": "D3 ഡ്രെക്കാന",
        "D30 Trimsamsa": "D30 ത്രിംസംസ",
        "D4 Chaturthamsa": "D4 ചതുർത്ഥാംശം",
        "D40 Khavedamsa": "D40 ഖവേദംസ",
        "D6 Bodily Humors": "D6 ശാരീരിക നർമ്മം",
        "D60 Shashtiamsa": "D60 ഷഷ്ടിയാംശ",
        "D7 Saptamsa Matrix": "D7 സപ്തംസ മാട്രിക്സ്",
        "D8 Ashtamsa Matrix": "D8 അഷ്ടാംസ മാട്രിക്സ്",
        "D9 & 9th House Rectitude": "D9 & 9th House റെക്റ്റിറ്റിയൂഡ്",
        "D9 Navamsa Harmony": "D9 നവാംസ ഹാർമണി",
        "Dosha Mitigation": "ദോഷ ലഘൂകരണം",
        "Maraka & Badhaka": "മാരക & ബധക",
        "Muhurta aligns human action with divine time. What auspicious event are you planning?": "മുഹൂർത്തം മനുഷ്യൻ്റെ പ്രവർത്തനത്തെ ദൈവിക സമയവുമായി യോജിപ്പിക്കുന്നു. എന്ത് ശുഭകരമായ പരിപാടിയാണ് നിങ്ങൾ ആസൂത്രണം ചെയ്യുന്നത്?",
        "Panchanga Engine": "പഞ്ചാംഗ എഞ്ചിൻ",
        "Swapna Shastra": "സ്വപ്ന ശാസ്ത്രം",
        "The 10th house governs your livelihood, daily trade, and standing before employers. What is the state of your work?": "പത്താം ഭാവം നിങ്ങളുടെ ഉപജീവനമാർഗം, ദൈനംദിന വ്യാപാരം, തൊഴിലുടമകളുടെ മുന്നിൽ നിൽക്കൽ എന്നിവയെ നിയന്ത്രിക്കുന്നു. നിങ്ങളുടെ ജോലിയുടെ അവസ്ഥ എന്താണ്?",
        "The 11th house dictates your ability to extract wealth and favors from large societies or guilds. What is the objective?": "വലിയ സമൂഹങ്ങളിൽ നിന്നോ ഗിൽഡുകളിൽ നിന്നോ സമ്പത്തും ആനുകൂല്യങ്ങളും വേർതിരിച്ചെടുക്കാനുള്ള നിങ്ങളുടെ കഴിവിനെ 11-ാം വീട് നിർദ്ദേശിക്കുന്നു. എന്താണ് ലക്ഷ്യം?",
        "The 11th house signifies the networks and companions we choose. Are your friends true allies or hidden drains?": "11-ാമത്തെ വീട് നമ്മൾ തിരഞ്ഞെടുക്കുന്ന നെറ്റ്‌വർക്കുകളേയും കൂട്ടാളികളേയും സൂചിപ്പിക്കുന്നു. നിങ്ങളുടെ സുഹൃത്തുക്കൾ യഥാർത്ഥ സഖ്യകക്ഷികളാണോ അതോ മറഞ്ഞിരിക്കുന്ന ഡ്രെയിനുകളാണോ?",
        "The 2nd house and D2 chart govern accumulated treasures, gold, and grains. What is your material focus?": "സമാഹരിച്ച നിധികൾ, സ്വർണ്ണം, ധാന്യങ്ങൾ എന്നിവയെ നിയന്ത്രിക്കുന്നത് രണ്ടാം വീടും D2 ചാർട്ടും ആണ്. നിങ്ങളുടെ മെറ്റീരിയൽ ഫോക്കസ് എന്താണ്?",
        "The 2nd house rules what enters the mouth. Diet directly shapes consciousness and physical destiny. What are you consuming?": "വായിൽ പ്രവേശിക്കുന്നതിനെ രണ്ടാം വീട് നിയന്ത്രിക്കുന്നു. ഭക്ഷണക്രമം ബോധവും ശാരീരിക വിധിയും നേരിട്ട് രൂപപ്പെടുത്തുന്നു. നിങ്ങൾ എന്താണ് കഴിക്കുന്നത്?",
        "The 3rd house governs the hands; the 5th governs creative intelligence. Are you honing your innate God-given skills?": "മൂന്നാം വീട് കൈകളെ ഭരിക്കുന്നു; അഞ്ചാമത്തേത് സർഗ്ഗാത്മക ബുദ്ധിയെ നിയന്ത്രിക്കുന്നു. നിങ്ങളുടെ സഹജമായ ദൈവം നൽകിയ കഴിവുകൾ നിങ്ങൾ മാനിക്കുകയാണോ?",
        "The 3rd house rules valor (Parakrama), siblings, and the right arm. Where is your courage directed?": "മൂന്നാം ഭാവം പരാക്രമം (പരാക്രമം), സഹോദരങ്ങൾ, വലതു കൈ എന്നിവയെ ഭരിക്കുന്നു. നിങ്ങളുടെ ധൈര്യം എവിടെയാണ് നയിക്കുന്നത്?",
        "The 4th house and Venus dictate your comfort in travel, ownership of vehicles, beasts of burden, and daily transport. Is your carriage secure?": "യാത്ര, വാഹനങ്ങളുടെ ഉടമസ്ഥാവകാശം, ഭാരമുള്ള മൃഗങ്ങൾ, ദൈനംദിന ഗതാഗതം എന്നിവയിൽ നിങ്ങളുടെ സുഖസൗകര്യങ്ങൾ നാലാം ഭാവവും ശുക്രനും നിർദ്ദേശിക്കുന്നു. നിങ്ങളുടെ വണ്ടി സുരക്ഷിതമാണോ?",
        "The 4th house governs fixed assets, land, and the comfort of the home. What earthly matter arises?": "4-ആം വീട് സ്ഥിര ആസ്തികൾ, ഭൂമി, വീടിൻ്റെ സുഖസൗകര്യങ്ങൾ എന്നിവ നിയന്ത്രിക്കുന്നു. എന്ത് ഭൗമിക ദ്രവ്യമാണ് ഉണ്ടാകുന്നത്?",
        "The 6th house dictates your relation to hard physical labor, servants, employees, and those lower in the social hierarchy. How do you manage the toil?": "കഠിനമായ ശാരീരിക അദ്ധ്വാനം, ജോലിക്കാർ, ജീവനക്കാർ, സാമൂഹിക ശ്രേണിയിൽ താഴെയുള്ളവർ എന്നിവരുമായുള്ള നിങ്ങളുടെ ബന്ധത്തെ 6-ാം വീട് നിർദ്ദേശിക്കുന്നു. നിങ്ങൾ എങ്ങനെയാണ് അധ്വാനം കൈകാര്യം ചെയ്യുന്നത്?",
        "The 6th house governs open enemies, disputes, and royal punishments. What conflict plagues you?": "ആറാമത്തെ വീട് തുറന്ന ശത്രുക്കൾ, തർക്കങ്ങൾ, രാജകീയ ശിക്ഷകൾ എന്നിവ നിയന്ത്രിക്കുന്നു. എന്ത് സംഘർഷമാണ് നിങ്ങളെ അലട്ടുന്നത്?",
        "The 6th house requires the rhythmic discipline of daily life to suppress diseases and enemies. What needs correction?": "രോഗങ്ങളെയും ശത്രുക്കളെയും അടിച്ചമർത്താൻ ആറാം ഭാവത്തിന് ദൈനംദിന ജീവിതത്തിൽ താളാത്മകമായ അച്ചടക്കം ആവശ്യമാണ്. എന്താണ് തിരുത്തൽ വേണ്ടത്?",
        "The 6th house rules Shadripu (the six enemies of the mind). Kama, Krodha, Lobha, Moha, Mada, Matsarya. Which vice has taken the reins?": "ആറാം വീട് ഷദ്രിപു (മനസ്സിൻ്റെ ആറ് ശത്രുക്കൾ) ഭരിക്കുന്നു. കാമ, ക്രോധ, ലോഭ, മോഹ, മദ, മാത്സര്യം. ഏത് വൈസ് ആണ് ഭരണം ഏറ്റെടുത്തത്?",
        "The 6th house tracks the heavy karmic chains of Runa (Debt). Are you bound to creditors, or are others bound to you?": "ആറാമത്തെ വീട് റൂണയുടെ (കടം) കനത്ത കർമ്മ ശൃംഖലകളെ ട്രാക്ക് ചെയ്യുന്നു. നിങ്ങൾ കടക്കാരോട് ബന്ധിതനാണോ, അതോ മറ്റുള്ളവർ നിങ്ങളോട് ബാധ്യസ്ഥരാണോ?",
        "The 8th house and D8 chart govern Tantra, hidden dimension, and the manipulation of occult energies. Do you dare look?": "എട്ടാമത്തെ വീടും D8 ചാർട്ടും തന്ത്രം, മറഞ്ഞിരിക്കുന്ന മാനം, നിഗൂഢ ഊർജ്ജങ്ങളുടെ കൃത്രിമത്വം എന്നിവ നിയന്ത്രിക്കുന്നു. നോക്കാൻ ധൈര്യമുണ്ടോ?",
        "The 8th house rules unearned wealth, buried treasures, and sudden reversals. What hidden matter stirs?": "എട്ടാം വീട് സമ്പാദിക്കാത്ത സമ്പത്ത്, കുഴിച്ചിട്ട നിധികൾ, പെട്ടെന്നുള്ള തിരിച്ചടവ് എന്നിവ നിയന്ത്രിക്കുന്നു. എന്താണ് മറഞ്ഞിരിക്കുന്ന കാര്യം ഇളക്കിവിടുന്നത്?",
        "The 9th house connects you to the deep, unshakable roots of your ancestors, language, and cultural rituals. Are you tethered or drifting?": "നിങ്ങളുടെ പൂർവ്വികർ, ഭാഷ, സാംസ്കാരിക ആചാരങ്ങൾ എന്നിവയുടെ ആഴമേറിയതും അചഞ്ചലവുമായ വേരുകളിലേക്ക് 9-ാം വീട് നിങ്ങളെ ബന്ധിപ്പിക്കുന്നു. നിങ്ങൾ കെട്ടിയിട്ടിരിക്കുകയാണോ അതോ ഡ്രിഫ്റ്റിംഗ് ചെയ്യുകയാണോ?",
        "The Arudha Lagna dictates the Maya—how the world perceives your status and renown. What is your public aim?": "ആരൂഢ ലഗ്നം മായയെ നിർദ്ദേശിക്കുന്നു - ലോകം നിങ്ങളുടെ പദവിയും പ്രശസ്തിയും എങ്ങനെ കാണുന്നു. നിങ്ങളുടെ പൊതുലക്ഷ്യം എന്താണ്?",
        "The D12 chart reveals the absolute karmic ties to the mother and father. What is the inquiry?": "D12 ചാർട്ട് അമ്മയോടും പിതാവിനോടുമുള്ള സമ്പൂർണ്ണ കർമ്മ ബന്ധങ്ങൾ വെളിപ്പെടുത്തുന്നു. എന്താണ് അന്വേഷണം?",
        "The D20 charts your spiritual receptivity and readiness for Mantra Diksha. Are you prepared to receive?": "നിങ്ങളുടെ ആത്മീയ സ്വീകാര്യതയും മന്ത്രദീക്ഷയ്ക്കുള്ള സന്നദ്ധതയും D20 ചാർട്ട് ചെയ്യുന്നു. സ്വീകരിക്കാൻ നിങ്ങൾ തയ്യാറാണോ?",
        "The D6 map exposes imbalances in the Vata, Pitta, and Kapha doshas. What anomaly requires attention?": "D6 മാപ്പ് വാത, പിത്ത, കഫ ദോഷങ്ങളിലെ അസന്തുലിതാവസ്ഥ വെളിപ്പെടുത്തുന്നു. എന്ത് അപാകതയ്ക്ക് ശ്രദ്ധ ആവശ്യമാണ്?",
        "The Maraka (Death-inflicting) houses command periods of immense physical danger. Scan for immediate threats.": "മാരക (മരണത്തിന് കാരണമാകുന്ന) ഭവനങ്ങൾ വലിയ ശാരീരിക അപകടത്തിൻ്റെ കാലഘട്ടങ്ങളാണ്. പെട്ടെന്നുള്ള ഭീഷണികൾക്കായി സ്കാൻ ചെയ്യുക.",
        "The expansion of the bloodline is governed by the 5th house. What concerns the legacy of your lineage?": "രക്തബന്ധത്തിൻ്റെ വികാസം നിയന്ത്രിക്കുന്നത് അഞ്ചാമത്തെ വീടാണ്. നിങ്ങളുടെ വംശപാരമ്പര്യത്തെ ബാധിക്കുന്നതെന്താണ്?",
        "The foundation of life rests upon Righteousness (Dharma). Which aspect of duty seeks clarity?": "ജീവിതത്തിൻ്റെ അടിസ്ഥാനം നീതിയിൽ (ധർമ്മം) അധിഷ്ഠിതമാണ്. ഡ്യൂട്ടിയുടെ ഏത് വശമാണ് വ്യക്തത തേടുന്നത്?",
        "The management of beasts, pets, and agricultural livestock falls under the 6th house. How is your relationship with the silent beings?": "മൃഗങ്ങൾ, വളർത്തുമൃഗങ്ങൾ, കാർഷിക കന്നുകാലികൾ എന്നിവയുടെ പരിപാലനം ആറാമത്തെ വീടിൻ്റെ കീഴിലാണ്. നിശബ്ദ ജീവികളുമായുള്ള നിങ്ങളുടെ ബന്ധം എങ്ങനെയുണ്ട്?",
        "The pursuit of Vidya removes darkness. What intellectual or spiritual knowledge do you seek?": "വിദ്യയെ പിന്തുടരുന്നത് ഇരുട്ടിനെ അകറ്റുന്നു. എന്ത് ബുദ്ധിപരമോ ആത്മീയമോ ആയ അറിവാണ് നിങ്ങൾ അന്വേഷിക്കുന്നത്?",
        "The sacred union of Vivaha binds two souls karmically. What is your inquiry regarding marital bonds?": "വിവാഹത്തിൻ്റെ പവിത്രമായ ഐക്യം രണ്ട് ആത്മാക്കളെ കർമ്മപരമായി ബന്ധിപ്പിക്കുന്നു. വൈവാഹിക ബന്ധങ്ങളെക്കുറിച്ചുള്ള നിങ്ങളുടെ അന്വേഷണമെന്താണ്?",
        "The subconscious mind receives signals from the astral plane. What omens are manifesting?": "ഉപബോധ മനസ്സിന് ആസ്ട്രൽ തലത്തിൽ നിന്ന് സിഗ്നലുകൾ ലഭിക്കുന്നു. എന്ത് ശകുനങ്ങളാണ് പ്രകടമാകുന്നത്?",
        "The ultimate aim is liberation from the cycle of birth and death. What blocks your spiritual ascent?": "ജനനമരണ ചക്രത്തിൽ നിന്നുള്ള മോചനമാണ് പരമമായ ലക്ഷ്യം. നിങ്ങളുടെ ആത്മീയ ഉയർച്ചയെ തടയുന്നതെന്താണ്?",
        "Travel for spiritual merit or foreign expansion requires alignment. What is the nature of the journey?": "ആത്മീയ യോഗ്യതയ്‌ക്കോ വിദേശ വികാസത്തിനോ വേണ്ടിയുള്ള യാത്രകൾക്ക് വിന്യാസം ആവശ്യമാണ്. യാത്രയുടെ സ്വഭാവം എന്താണ്?",
        "True wealth is internal peace (Sukha) and a harmonious home. What disturbs the waters of the mind?": "ആന്തരിക സമാധാനവും (സുഖ) യോജിപ്പുള്ള ഭവനവുമാണ് യഥാർത്ഥ സമ്പത്ത്. മനസ്സിലെ ജലത്തെ അസ്വസ്ഥമാക്കുന്നത് എന്താണ്?",
        "We carry the unsolved debts of our forefathers. What ancestral affliction requires propitiation?": "നമ്മുടെ പൂർവികരുടെ പരിഹരിക്കപ്പെടാത്ത കടങ്ങൾ ഞങ്ങൾ ചുമക്കുന്നു. ഏത് പൂർവ്വിക ക്ലേശങ്ങൾക്ക് പ്രായശ്ചിത്തം ആവശ്യമാണ്?",
        "Wealth that is hoarded rots the soul. Danam (Charity) is the great purifier of the D2 treasury. Where must your resources flow?": "സ്വരൂപിക്കുന്ന സമ്പത്ത് ആത്മാവിനെ ചീത്തയാക്കുന്നു. D2 ട്രഷറിയുടെ വലിയ ശുദ്ധീകരണമാണ് ദാനം (ചാരിറ്റി). നിങ്ങളുടെ വിഭവങ്ങൾ എവിടെയാണ് ഒഴുകേണ്ടത്?"
    },
    "mr": {
        "10th House Karma": "10 व्या घरातील कर्म",
        "11th House Bonds": "11 व्या घराचे रोखे",
        "11th House Gains": "11 व्या घरातील नफा",
        "12th/5th House Release": "१२ वी/५वी हाऊस रिलीज",
        "12th/9th House Vectors": "12 वी/9वी हाऊस वेक्टर",
        "2nd House Sustenance": "2 रा हाऊस सस्टेनन्स",
        "3rd/5th House Skills": "3री/5वी गृह कौशल्ये",
        "4th House Mobility": "चौथ्या घराची गतिशीलता",
        "4th House Tranquility": "चौथ्या घरात शांतता",
        "6th House Afflictions": "6 व्या घरातील क्लेश",
        "6th House Companions": "6 व्या घरातील साथीदार",
        "6th House Discipline": "6 व्या घराची शिस्त",
        "6th House Ledgers": "6 व्या हाऊस लेजर",
        "6th/Saturn Karma": "6 वा शनि कर्म",
        "8th House Mysteries": "8 व्या घराची रहस्ये",
        "9th House Philanthropy": "9व्या घरातील परोपकार",
        "9th House Roots": "9 व्या घराची मुळे",
        "Afflictions demand propitiation. Which traditional remedial measure do you seek to enact?": "दु:ख प्रायश्चिताची मागणी करतात. तुम्ही कोणते पारंपारिक उपचार उपाय लागू करू इच्छिता?",
        "Arudha Lagna Profile": "अरुधा लग्न प्रोफाइल",
        "Between the grinding gears of Dharma and Artha, the soul requires Vishrama (rest) and playful release to maintain sanity. How do you retreat?": "धर्म आणि अर्थाच्या ग्राइंडिंग गियर्स दरम्यान, आत्म्याला विवेक (विश्रांती) आणि चंचल मुक्ती आवश्यक आहे. आपण मागे कसे?",
        "D12 Dwadasamsa": "D12 द्वादसंसा",
        "D2 Hora Liquidity": "D2 होरा तरलता",
        "D20 Vimsamsa": "D20 Vimsamsa",
        "D24 Chaturvimsamsa": "D24 चातुर्विमसंसा",
        "D3 Drekkana": "D3 Drekkana",
        "D30 Trimsamsa": "D30 Trimsamsa",
        "D4 Chaturthamsa": "D4 चतुर्थम्सा",
        "D40 Khavedamsa": "D40 खावेदमसा",
        "D6 Bodily Humors": "D6 शारीरिक विनोद",
        "D60 Shashtiamsa": "D60 षष्ठीमसा",
        "D7 Saptamsa Matrix": "D7 सप्तम्स मॅट्रिक्स",
        "D8 Ashtamsa Matrix": "D8 अष्टम्स मॅट्रिक्स",
        "D9 & 9th House Rectitude": "D9 आणि 9व्या घराची अचूकता",
        "D9 Navamsa Harmony": "D9 नवंसा सुसंवाद",
        "Dosha Mitigation": "दोष शमन",
        "Maraka & Badhaka": "मारका आणि बधका",
        "Muhurta aligns human action with divine time. What auspicious event are you planning?": "मुहूर्त मानवी क्रिया दैवी काळाशी संरेखित करतो. तुम्ही कोणत्या शुभ कार्यक्रमाची योजना आखत आहात?",
        "Panchanga Engine": "पंचांग इंजिन",
        "Swapna Shastra": "स्वप्नशास्त्र",
        "The 10th house governs your livelihood, daily trade, and standing before employers. What is the state of your work?": "10 वे घर तुमची उपजीविका, दैनंदिन व्यापार आणि नियोक्त्यांसमोर उभे राहण्याचे नियमन करते. तुमच्या कामाची स्थिती काय आहे?",
        "The 11th house dictates your ability to extract wealth and favors from large societies or guilds. What is the objective?": "11 वे घर मोठ्या समाज किंवा गिल्डमधून संपत्ती आणि अनुकूलता मिळविण्याची तुमची क्षमता ठरवते. उद्दिष्ट काय आहे?",
        "The 11th house signifies the networks and companions we choose. Are your friends true allies or hidden drains?": "11 वे घर आम्ही निवडलेले नेटवर्क आणि साथीदार दर्शवते. तुमचे मित्र खरे मित्र आहेत की छुपे नाले आहेत?",
        "The 2nd house and D2 chart govern accumulated treasures, gold, and grains. What is your material focus?": "2रे घर आणि D2 चार्ट जमा झालेला खजिना, सोने आणि धान्य नियंत्रित करतात. तुमचे भौतिक लक्ष काय आहे?",
        "The 2nd house rules what enters the mouth. Diet directly shapes consciousness and physical destiny. What are you consuming?": "तोंडात काय जाते ते 2रे घर नियम करते. आहार थेट चेतना आणि शारीरिक नशिबाला आकार देतो. तुम्ही काय सेवन करत आहात?",
        "The 3rd house governs the hands; the 5th governs creative intelligence. Are you honing your innate God-given skills?": "3 रा घर हात नियंत्रित करते; 5 वी सर्जनशील बुद्धिमत्ता नियंत्रित करते. तुम्ही तुमच्या जन्मजात देवाने दिलेल्या कौशल्यांचा सन्मान करत आहात का?",
        "The 3rd house rules valor (Parakrama), siblings, and the right arm. Where is your courage directed?": "तिसरे घर शौर्य (पराक्रम), भावंड आणि उजव्या हातावर नियम करते. तुमचे धैर्य कोठे निर्देशित केले आहे?",
        "The 4th house and Venus dictate your comfort in travel, ownership of vehicles, beasts of burden, and daily transport. Is your carriage secure?": "चौथे घर आणि शुक्र तुमचा प्रवास, वाहनांची मालकी, ओझे असलेले प्राणी आणि दैनंदिन वाहतुकीमध्ये आराम करतात. तुमची गाडी सुरक्षित आहे का?",
        "The 4th house governs fixed assets, land, and the comfort of the home. What earthly matter arises?": "चौथ्या घरामध्ये स्थिर मालमत्ता, जमीन आणि घरातील सोई यावर नियंत्रण होते. पृथ्वीवरील कोणते पदार्थ उद्भवतात?",
        "The 6th house dictates your relation to hard physical labor, servants, employees, and those lower in the social hierarchy. How do you manage the toil?": "6 वे घर कठोर शारीरिक श्रम, नोकर, कर्मचारी आणि सामाजिक पदानुक्रमात खालच्या लोकांशी तुमचे संबंध ठरवते. तुम्ही कष्टाचे व्यवस्थापन कसे करता?",
        "The 6th house governs open enemies, disputes, and royal punishments. What conflict plagues you?": "6 वे घर उघडे शत्रू, विवाद आणि शाही शिक्षा नियंत्रित करते. तुम्हाला कोणता संघर्ष त्रास देतो?",
        "The 6th house requires the rhythmic discipline of daily life to suppress diseases and enemies. What needs correction?": "6 व्या घराला रोग आणि शत्रूंना दडपण्यासाठी दैनंदिन जीवनातील लयबद्ध शिस्तीची आवश्यकता आहे. काय सुधारणा आवश्यक आहे?",
        "The 6th house rules Shadripu (the six enemies of the mind). Kama, Krodha, Lobha, Moha, Mada, Matsarya. Which vice has taken the reins?": "सहाव्या घरावर षड्रिपू (मनाचे सहा शत्रू) राज्य करतात. काम, क्रोधा, लोभा, मोह, मद, मत्सर्य. कोणत्या दुर्गुणांनी लगाम घेतला आहे?",
        "The 6th house tracks the heavy karmic chains of Runa (Debt). Are you bound to creditors, or are others bound to you?": "6 वे घर रुना (कर्ज) च्या जड कर्मिक साखळ्यांचा मागोवा घेते. तुम्ही कर्जदारांशी बांधील आहात की इतर तुमच्याशी बांधील आहेत?",
        "The 8th house and D8 chart govern Tantra, hidden dimension, and the manipulation of occult energies. Do you dare look?": "8 वे घर आणि D8 चार्ट तंत्र, लपलेले परिमाण आणि गूढ उर्जेची हाताळणी नियंत्रित करतात. बघण्याची हिम्मत आहे का?",
        "The 8th house rules unearned wealth, buried treasures, and sudden reversals. What hidden matter stirs?": "8 व्या घरामध्ये अनर्जित संपत्ती, दफन केलेला खजिना आणि अचानक उलटसुलट गोष्टींवर राज्य केले जाते. कोणते लपलेले पदार्थ ढवळतात?",
        "The 9th house connects you to the deep, unshakable roots of your ancestors, language, and cultural rituals. Are you tethered or drifting?": "9 वे घर तुम्हाला तुमच्या पूर्वजांच्या खोल, अटल मुळांशी, भाषा आणि सांस्कृतिक संस्कारांशी जोडते. तुम्ही टेथर्ड किंवा ड्रिफ्टिंग आहात?",
        "The Arudha Lagna dictates the Maya—how the world perceives your status and renown. What is your public aim?": "अरुधा लग्न माया ठरवते - जगाला तुमची स्थिती आणि कीर्ती कशी समजते. तुमचे सार्वजनिक उद्दिष्ट काय आहे?",
        "The D12 chart reveals the absolute karmic ties to the mother and father. What is the inquiry?": "D12 चार्ट आई आणि वडिलांचे पूर्ण कर्मिक संबंध प्रकट करतो. चौकशी काय?",
        "The D20 charts your spiritual receptivity and readiness for Mantra Diksha. Are you prepared to receive?": "D20 तुमची अध्यात्मिक ग्रहणक्षमता आणि मंत्र दीक्षेची तयारी दर्शवते. आपण प्राप्त करण्यास तयार आहात?",
        "The D6 map exposes imbalances in the Vata, Pitta, and Kapha doshas. What anomaly requires attention?": "D6 नकाशा वात, पित्त आणि कफ दोषांमधील असंतुलन उघड करतो. कोणत्या विसंगतीकडे लक्ष देणे आवश्यक आहे?",
        "The Maraka (Death-inflicting) houses command periods of immense physical danger. Scan for immediate threats.": "मराका (मृत्यूला झेपावणारी) घरे प्रचंड शारीरिक धोक्याची आज्ञा देतात. तत्काळ धमक्यांसाठी स्कॅन करा.",
        "The expansion of the bloodline is governed by the 5th house. What concerns the legacy of your lineage?": "रक्तरेषेचा विस्तार 5 व्या घराद्वारे नियंत्रित केला जातो. तुमच्या वंशाच्या वारशाची काय चिंता आहे?",
        "The foundation of life rests upon Righteousness (Dharma). Which aspect of duty seeks clarity?": "जीवनाचा पाया धार्मिकतेवर (धर्म) आहे. कर्तव्याच्या कोणत्या पैलूमध्ये स्पष्टता हवी आहे?",
        "The management of beasts, pets, and agricultural livestock falls under the 6th house. How is your relationship with the silent beings?": "पशू, पाळीव प्राणी आणि कृषी पशुधन यांचे व्यवस्थापन 6 व्या घराच्या अंतर्गत येते. मूक प्राण्यांशी तुमचे नाते कसे आहे?",
        "The pursuit of Vidya removes darkness. What intellectual or spiritual knowledge do you seek?": "विद्या साधनेने अंधार दूर होतो. तुम्ही कोणते बौद्धिक किंवा आध्यात्मिक ज्ञान शोधता?",
        "The sacred union of Vivaha binds two souls karmically. What is your inquiry regarding marital bonds?": "विवाहाचे पवित्र मिलन दोन आत्म्यांना कर्माने बांधते. वैवाहिक बंधनांबाबत तुमची चौकशी काय आहे?",
        "The subconscious mind receives signals from the astral plane. What omens are manifesting?": "अवचेतन मन सूक्ष्म विमानातून सिग्नल प्राप्त करते. कोणती चिन्हे प्रकट होत आहेत?",
        "The ultimate aim is liberation from the cycle of birth and death. What blocks your spiritual ascent?": "जन्म-मृत्यूच्या फेऱ्यातून मुक्ती हेच अंतिम ध्येय आहे. तुमची आध्यात्मिक चढाई कशामुळे अडवते?",
        "Travel for spiritual merit or foreign expansion requires alignment. What is the nature of the journey?": "आध्यात्मिक गुणवत्तेसाठी किंवा परदेशी विस्तारासाठी प्रवास करण्यासाठी संरेखन आवश्यक आहे. प्रवासाचे स्वरूप काय आहे?",
        "True wealth is internal peace (Sukha) and a harmonious home. What disturbs the waters of the mind?": "खरी संपत्ती ही आंतरिक शांती (सुखा) आणि सुसंवादी घर आहे. मनाच्या पाण्याला कशाने त्रास होतो?",
        "We carry the unsolved debts of our forefathers. What ancestral affliction requires propitiation?": "आमच्या पूर्वजांचे न सुटलेले ऋण आम्ही वाहतो. कोणत्या वडिलोपार्जित दुःखासाठी प्रायश्चित्त आवश्यक आहे?",
        "Wealth that is hoarded rots the soul. Danam (Charity) is the great purifier of the D2 treasury. Where must your resources flow?": "साठवलेली संपत्ती आत्म्याला कुजवते. दानम (चॅरिटी) हा D2 कोषाचा महान शुद्धकर्ता आहे. तुमची संसाधने कोठे प्रवाहित केली पाहिजेत?"
    },
    "gu": {
        "10th House Karma": "10મું ઘર કર્મ",
        "11th House Bonds": "11 મી હાઉસ બોન્ડ્સ",
        "11th House Gains": "11મી ગૃહ લાભો",
        "12th/5th House Release": "12મી/5મી હાઉસ રિલીઝ",
        "12th/9th House Vectors": "12મી/9મી હાઉસ વેક્ટર",
        "2nd House Sustenance": "2જી ગૃહ નિર્વાહ",
        "3rd/5th House Skills": "3જી/5મી ગૃહ કુશળતા",
        "4th House Mobility": "4 થી હાઉસ ગતિશીલતા",
        "4th House Tranquility": "4 થી ઘરની શાંતિ",
        "6th House Afflictions": "6ઠ્ઠી ઘરની તકલીફો",
        "6th House Companions": "6ઠ્ઠું ઘર સાથીદાર",
        "6th House Discipline": "6ઠ્ઠું ગૃહ શિસ્ત",
        "6th House Ledgers": "6ઠ્ઠું હાઉસ લેજર્સ",
        "6th/Saturn Karma": "6મો/શનિ કર્મ",
        "8th House Mysteries": "8 મી હાઉસ મિસ્ટ્રીઝ",
        "9th House Philanthropy": "9મું ઘર પરોપકાર",
        "9th House Roots": "9 મી હાઉસ રૂટ્સ",
        "Afflictions demand propitiation. Which traditional remedial measure do you seek to enact?": "દુ:ખો પ્રાયશ્ચિતની માંગ કરે છે. તમે કયા પરંપરાગત ઉપચારાત્મક પગલાંને અમલમાં મૂકવાનો પ્રયાસ કરો છો?",
        "Arudha Lagna Profile": "અરુધા લગ્ન પ્રોફાઇલ",
        "Between the grinding gears of Dharma and Artha, the soul requires Vishrama (rest) and playful release to maintain sanity. How do you retreat?": "ધર્મ અને અર્થના ગ્રાઇન્ડીંગ ગિયર્સ વચ્ચે, આત્માને વિશ્રામ (વિશ્રામ) અને વિવેક જાળવવા માટે રમતિયાળ મુક્તિની જરૂર છે. તમે કેવી રીતે પીછેહઠ કરશો?",
        "D12 Dwadasamsa": "D12 દ્વાદશાં",
        "D2 Hora Liquidity": "D2 હોરા લિક્વિડિટી",
        "D20 Vimsamsa": "D20 Vimsamsa",
        "D24 Chaturvimsamsa": "D24 ચતુર્વિંસંસા",
        "D3 Drekkana": "ડી 3 ડ્રેક્કાના",
        "D30 Trimsamsa": "D30 Trimsamsa",
        "D4 Chaturthamsa": "D4 ચતુર્થમસા",
        "D40 Khavedamsa": "D40 Khavedamsa",
        "D6 Bodily Humors": "D6 શારીરિક રમૂજ",
        "D60 Shashtiamsa": "D60 ષષ્ટીયમસા",
        "D7 Saptamsa Matrix": "D7 સપ્તમસ મેટ્રિક્સ",
        "D8 Ashtamsa Matrix": "D8 અષ્ટમસા મેટ્રિક્સ",
        "D9 & 9th House Rectitude": "D9 અને 9મું ઘર સુધારણા",
        "D9 Navamsa Harmony": "D9 નવમસંવાદિતા",
        "Dosha Mitigation": "દોષ શમન",
        "Maraka & Badhaka": "મારકા અને બધકા",
        "Muhurta aligns human action with divine time. What auspicious event are you planning?": "મુહૂર્ત માનવ ક્રિયાને દૈવી સમય સાથે સંરેખિત કરે છે. તમે કઈ શુભ ઘટનાનું આયોજન કરી રહ્યા છો?",
        "Panchanga Engine": "પંચાંગ એન્જિન",
        "Swapna Shastra": "સ્વપ્ન શાસ્ત્ર",
        "The 10th house governs your livelihood, daily trade, and standing before employers. What is the state of your work?": "10મું ઘર તમારી આજીવિકા, દૈનિક વેપાર અને નોકરીદાતાઓ સમક્ષ ઊભા રહેવાનું સંચાલન કરે છે. તમારા કામની સ્થિતિ શું છે?",
        "The 11th house dictates your ability to extract wealth and favors from large societies or guilds. What is the objective?": "11મું ઘર મોટા સમાજ અથવા મહાજનમાંથી સંપત્તિ અને તરફેણ મેળવવાની તમારી ક્ષમતા નક્કી કરે છે. ઉદ્દેશ્ય શું છે?",
        "The 11th house signifies the networks and companions we choose. Are your friends true allies or hidden drains?": "11મું ઘર અમે પસંદ કરેલા નેટવર્ક અને સાથીદારોને દર્શાવે છે. શું તમારા મિત્રો સાચા સાથી છે કે છુપાયેલા ગટર?",
        "The 2nd house and D2 chart govern accumulated treasures, gold, and grains. What is your material focus?": "2જી ઘર અને D2 ચાર્ટ સંચિત ખજાના, સોનું અને અનાજને નિયંત્રિત કરે છે. તમારું ભૌતિક ધ્યાન શું છે?",
        "The 2nd house rules what enters the mouth. Diet directly shapes consciousness and physical destiny. What are you consuming?": "2 જી ઘર મોંમાં શું પ્રવેશ કરે છે તેનું નિયમન કરે છે. આહાર ચેતના અને ભૌતિક ભાગ્યને સીધો આકાર આપે છે. તમે શું સેવન કરો છો?",
        "The 3rd house governs the hands; the 5th governs creative intelligence. Are you honing your innate God-given skills?": "3 જી ગૃહ હાથનું સંચાલન કરે છે; 5મી સર્જનાત્મક બુદ્ધિનું સંચાલન કરે છે. શું તમે તમારી જન્મજાત ઈશ્વરે આપેલી કુશળતાને સન્માનિત કરો છો?",
        "The 3rd house rules valor (Parakrama), siblings, and the right arm. Where is your courage directed?": "ત્રીજું ઘર પરાક્રમ (પરાક્રમ), ભાઈ-બહેન અને જમણા હાથનું નિયમન કરે છે. તમારી હિંમત ક્યાં નિર્દેશિત છે?",
        "The 4th house and Venus dictate your comfort in travel, ownership of vehicles, beasts of burden, and daily transport. Is your carriage secure?": "ચોથું ઘર અને શુક્ર મુસાફરી, વાહનોની માલિકી, બોજારૂપ જાનવરો અને દૈનિક વાહનવ્યવહારમાં તમારા આરામનું નિર્દેશન કરે છે. શું તમારી ગાડી સુરક્ષિત છે?",
        "The 4th house governs fixed assets, land, and the comfort of the home. What earthly matter arises?": "ચોથું ઘર સ્થિર સંપત્તિ, જમીન અને ઘરની આરામનું સંચાલન કરે છે. કઈ ધરતીનું દ્રવ્ય ઉદભવે છે?",
        "The 6th house dictates your relation to hard physical labor, servants, employees, and those lower in the social hierarchy. How do you manage the toil?": "6ઠ્ઠું ઘર સખત શારીરિક શ્રમ, નોકરો, કર્મચારીઓ અને સામાજિક વંશવેલોમાં નીચલા લોકો સાથેના તમારા સંબંધને સૂચવે છે. તમે મહેનતનું સંચાલન કેવી રીતે કરશો?",
        "The 6th house governs open enemies, disputes, and royal punishments. What conflict plagues you?": "6ઠ્ઠું ઘર ખુલ્લા દુશ્મનો, વિવાદો અને શાહી સજાઓનું સંચાલન કરે છે. તમને કયો સંઘર્ષ સતાવે છે?",
        "The 6th house requires the rhythmic discipline of daily life to suppress diseases and enemies. What needs correction?": "6ઠ્ઠું ઘર રોગો અને દુશ્મનોને દબાવવા માટે દૈનિક જીવનની લયબદ્ધ શિસ્તની જરૂર છે. શું કરેક્શનની જરૂર છે?",
        "The 6th house rules Shadripu (the six enemies of the mind). Kama, Krodha, Lobha, Moha, Mada, Matsarya. Which vice has taken the reins?": "6ઠ્ઠું ઘર શાદ્રિપુ (મનના છ દુશ્મનો) પર શાસન કરે છે. કામ, ક્રોધ, લોભા, મોહ, મદ, મત્સર્ય. ક્યા દૂષણે લગામ લીધી છે?",
        "The 6th house tracks the heavy karmic chains of Runa (Debt). Are you bound to creditors, or are others bound to you?": "6ઠ્ઠું ઘર રૂના (દેવું) ની ભારે કર્મની સાંકળો પર નજર રાખે છે. શું તમે લેણદારો સાથે બંધાયેલા છો, અથવા અન્ય લોકો તમારા માટે બંધાયેલા છે?",
        "The 8th house and D8 chart govern Tantra, hidden dimension, and the manipulation of occult energies. Do you dare look?": "8મું ઘર અને D8 ચાર્ટ તંત્ર, છુપાયેલા પરિમાણ અને ગુપ્ત શક્તિઓની હેરફેરનું સંચાલન કરે છે. શું તમે જોવાની હિંમત કરો છો?",
        "The 8th house rules unearned wealth, buried treasures, and sudden reversals. What hidden matter stirs?": "8મું ઘર અર્જિત સંપત્તિ, દફનાવવામાં આવેલા ખજાના અને અચાનક ઉલટાનું શાસન કરે છે. શું છુપાયેલ બાબત stirs?",
        "The 9th house connects you to the deep, unshakable roots of your ancestors, language, and cultural rituals. Are you tethered or drifting?": "9મું ઘર તમને તમારા પૂર્વજો, ભાષા અને સાંસ્કૃતિક સંસ્કારોના ઊંડા, અટલ મૂળ સાથે જોડે છે. શું તમે ટેથર્ડ છો અથવા ડ્રિફ્ટિંગ છો?",
        "The Arudha Lagna dictates the Maya—how the world perceives your status and renown. What is your public aim?": "અરુધા લગન માયાને સૂચવે છે - વિશ્વ તમારી સ્થિતિ અને પ્રતિષ્ઠાને કેવી રીતે સમજે છે. તમારો જાહેર હેતુ શું છે?",
        "The D12 chart reveals the absolute karmic ties to the mother and father. What is the inquiry?": "D12 ચાર્ટ માતા અને પિતા સાથેના સંપૂર્ણ કર્મ સંબંધોને દર્શાવે છે. શું છે પૂછપરછ?",
        "The D20 charts your spiritual receptivity and readiness for Mantra Diksha. Are you prepared to receive?": "D20 તમારી આધ્યાત્મિક ગ્રહણશક્તિ અને મંત્ર દીક્ષા માટેની તૈયારી દર્શાવે છે. શું તમે પ્રાપ્ત કરવા માટે તૈયાર છો?",
        "The D6 map exposes imbalances in the Vata, Pitta, and Kapha doshas. What anomaly requires attention?": "D6 નકશો વાત, પિત્ત અને કફ દોષોમાં અસંતુલનને ઉજાગર કરે છે. કઈ વિસંગતતાને ધ્યાન આપવાની જરૂર છે?",
        "The Maraka (Death-inflicting) houses command periods of immense physical danger. Scan for immediate threats.": "મરાકા (મૃત્યુ આપનાર) ઘરો ભારે શારીરિક જોખમના સમયગાળાને આદેશ આપે છે. તાત્કાલિક ધમકીઓ માટે સ્કેન કરો.",
        "The expansion of the bloodline is governed by the 5th house. What concerns the legacy of your lineage?": "બ્લડલાઇનનું વિસ્તરણ 5 મા ઘર દ્વારા સંચાલિત થાય છે. તમારા વંશના વારસાની ચિંતા શું છે?",
        "The foundation of life rests upon Righteousness (Dharma). Which aspect of duty seeks clarity?": "જીવનનો પાયો સચ્ચાઈ (ધર્મ) પર ટકેલો છે. ફરજનું કયું પાસું સ્પષ્ટતા માંગે છે?",
        "The management of beasts, pets, and agricultural livestock falls under the 6th house. How is your relationship with the silent beings?": "જાનવરો, પાલતુ પ્રાણીઓ અને કૃષિ પશુધનનું સંચાલન 6ઠ્ઠા ઘર હેઠળ આવે છે. શાંત માણસો સાથે તમારો સંબંધ કેવો છે?",
        "The pursuit of Vidya removes darkness. What intellectual or spiritual knowledge do you seek?": "વિદ્યાની પ્રાપ્તિ અંધકારને દૂર કરે છે. તમે કયું બૌદ્ધિક અથવા આધ્યાત્મિક જ્ઞાન શોધો છો?",
        "The sacred union of Vivaha binds two souls karmically. What is your inquiry regarding marital bonds?": "વિવાહનું પવિત્ર મિલન બે આત્માઓને કર્મથી બાંધે છે. વૈવાહિક બંધનો અંગે તમારી પૂછપરછ શું છે?",
        "The subconscious mind receives signals from the astral plane. What omens are manifesting?": "અર્ધજાગ્રત મન અપાર્થિવ વિમાનમાંથી સંકેતો મેળવે છે. કયા શુકનો પ્રગટ થાય છે?",
        "The ultimate aim is liberation from the cycle of birth and death. What blocks your spiritual ascent?": "અંતિમ ધ્યેય જન્મ અને મૃત્યુના ચક્રમાંથી મુક્તિ છે. તમારા આધ્યાત્મિક ચઢાણને શું અવરોધે છે?",
        "Travel for spiritual merit or foreign expansion requires alignment. What is the nature of the journey?": "આધ્યાત્મિક યોગ્યતા અથવા વિદેશી વિસ્તરણ માટે પ્રવાસ માટે સંરેખણની જરૂર છે. પ્રવાસનું સ્વરૂપ શું છે?",
        "True wealth is internal peace (Sukha) and a harmonious home. What disturbs the waters of the mind?": "સાચી સંપત્તિ આંતરિક શાંતિ (સુખા) અને સુમેળભર્યું ઘર છે. મનના પાણીને શું ખલેલ પહોંચાડે છે?",
        "We carry the unsolved debts of our forefathers. What ancestral affliction requires propitiation?": "અમે અમારા પૂર્વજોના વણઉકેલાયેલા ઋણ વહન કરીએ છીએ. કયા પૂર્વજોની વેદનાને પ્રાયશ્ચિત કરવાની જરૂર છે?",
        "Wealth that is hoarded rots the soul. Danam (Charity) is the great purifier of the D2 treasury. Where must your resources flow?": "જે સંપત્તિનો સંગ્રહ કરવામાં આવે છે તે આત્માને સડે છે. દાનમ (દાન) એ D2 તિજોરીનું મહાન શુદ્ધિકરણ છે. તમારા સંસાધનો ક્યાં વહેવા જોઈએ?"
    },
    "bn": {
        "10th House Karma": "দশম ঘরের কর্ম",
        "11th House Bonds": "11 তম হাউস বন্ড",
        "11th House Gains": "11 তম হাউস লাভ",
        "12th/5th House Release": "12ম/5ম হাউস রিলিজ",
        "12th/9th House Vectors": "12ম/9ম হাউস ভেক্টর",
        "2nd House Sustenance": "২য় ঘরের ভরণপোষণ",
        "3rd/5th House Skills": "3য়/5ম ঘরের দক্ষতা",
        "4th House Mobility": "4র্থ হাউস গতিশীলতা",
        "4th House Tranquility": "৪র্থ ঘরের প্রশান্তি",
        "6th House Afflictions": "6 ম ঘরের দুঃখকষ্ট",
        "6th House Companions": "৬ষ্ঠ ঘরের সঙ্গী",
        "6th House Discipline": "৬ষ্ঠ হাউস ডিসিপ্লিন",
        "6th House Ledgers": "৬ষ্ঠ হাউস লেজার",
        "6th/Saturn Karma": "৬ষ্ঠ/শনি কর্ম",
        "8th House Mysteries": "8 ম ঘর রহস্য",
        "9th House Philanthropy": "9ম হাউস ফিলানথ্রপি",
        "9th House Roots": "9ম ঘরের শিকড়",
        "Afflictions demand propitiation. Which traditional remedial measure do you seek to enact?": "দুঃখ-কষ্টের প্রতিশোধ দাবি করে। আপনি কোন ঐতিহ্যগত প্রতিকারমূলক ব্যবস্থা প্রণয়ন করতে চান?",
        "Arudha Lagna Profile": "অরুধা লগ্ন প্রোফাইল",
        "Between the grinding gears of Dharma and Artha, the soul requires Vishrama (rest) and playful release to maintain sanity. How do you retreat?": "ধর্ম এবং অর্থের নাকাল গিয়ারের মধ্যে, আত্মার বিশ্রাম (বিশ্রাম) এবং বিচক্ষণতা বজায় রাখার জন্য কৌতুকপূর্ণ মুক্তির প্রয়োজন। আপনি কিভাবে পশ্চাদপসরণ করবেন?",
        "D12 Dwadasamsa": "D12 দ্বাদশংস",
        "D2 Hora Liquidity": "D2 হোরা তারল্য",
        "D20 Vimsamsa": "D20 Vimsamsa",
        "D24 Chaturvimsamsa": "D24 চতুর্ভিংস",
        "D3 Drekkana": "D3 ড্রেক্কানা",
        "D30 Trimsamsa": "D30 Trimsamsa",
        "D4 Chaturthamsa": "D4 চতুর্থমশা",
        "D40 Khavedamsa": "D40 খাভেদামসা",
        "D6 Bodily Humors": "D6 শারীরিক হাস্যরস",
        "D60 Shashtiamsa": "D60 Shashtiamsa",
        "D7 Saptamsa Matrix": "D7 সপ্তম ম্যাট্রিক্স",
        "D8 Ashtamsa Matrix": "D8 অষ্টমসা ম্যাট্রিক্স",
        "D9 & 9th House Rectitude": "D9 এবং 9ম হাউস রেকটিটিউড",
        "D9 Navamsa Harmony": "D9 নবমসা হারমনি",
        "Dosha Mitigation": "দোষ প্রশমন",
        "Maraka & Badhaka": "মারাকা ও বাধাকা",
        "Muhurta aligns human action with divine time. What auspicious event are you planning?": "মুহুর্তা মানুষের কর্মকে ঐশ্বরিক সময়ের সাথে সারিবদ্ধ করে। আপনি কোন শুভ অনুষ্ঠানের পরিকল্পনা করছেন?",
        "Panchanga Engine": "পঞ্চাঙ্গ ইঞ্জিন",
        "Swapna Shastra": "স্বপ্নশাস্ত্র",
        "The 10th house governs your livelihood, daily trade, and standing before employers. What is the state of your work?": "10 তম ঘর আপনার জীবিকা, দৈনন্দিন বাণিজ্য, এবং নিয়োগকারীদের সামনে দাঁড়ানো নিয়ন্ত্রণ করে। আপনার কাজের অবস্থা কি?",
        "The 11th house dictates your ability to extract wealth and favors from large societies or guilds. What is the objective?": "11 তম ঘরটি বৃহৎ সমাজ বা গিল্ড থেকে সম্পদ এবং অনুগ্রহ আহরণ করার আপনার ক্ষমতা নির্দেশ করে। উদ্দেশ্য কি?",
        "The 11th house signifies the networks and companions we choose. Are your friends true allies or hidden drains?": "11 তম ঘরটি আমাদের বেছে নেওয়া নেটওয়ার্ক এবং সঙ্গীদেরকে বোঝায়। আপনার বন্ধুরা কি সত্যিকারের মিত্র নাকি লুকানো ড্রেন?",
        "The 2nd house and D2 chart govern accumulated treasures, gold, and grains. What is your material focus?": "2য় ঘর এবং D2 চার্ট সঞ্চিত ধন, সোনা এবং শস্য নিয়ন্ত্রণ করে। আপনার উপাদান ফোকাস কি?",
        "The 2nd house rules what enters the mouth. Diet directly shapes consciousness and physical destiny. What are you consuming?": "২য় ঘর নিয়ম করে যা মুখে প্রবেশ করে। খাদ্য সরাসরি চেতনা এবং শারীরিক ভাগ্য গঠন করে। আপনি কি গ্রাস করছেন?",
        "The 3rd house governs the hands; the 5th governs creative intelligence. Are you honing your innate God-given skills?": "3য় ঘর হাত শাসন করে; 5ম সৃজনশীল বুদ্ধিমত্তা নিয়ন্ত্রণ করে। আপনি কি আপনার সহজাত ঈশ্বর-প্রদত্ত দক্ষতাকে সম্মান করছেন?",
        "The 3rd house rules valor (Parakrama), siblings, and the right arm. Where is your courage directed?": "৩য় ঘর নিয়ম করে বীরত্ব (পর্যাক্রম), ভাইবোন, এবং ডান হাত। আপনার সাহস কোথায় নির্দেশিত?",
        "The 4th house and Venus dictate your comfort in travel, ownership of vehicles, beasts of burden, and daily transport. Is your carriage secure?": "4র্থ ঘর এবং শুক্র ভ্রমণ, যানবাহনের মালিকানা, বোঝার পশু এবং দৈনন্দিন পরিবহনে আপনার স্বাচ্ছন্দ্য নির্দেশ করে। আপনার গাড়ি কি নিরাপদ?",
        "The 4th house governs fixed assets, land, and the comfort of the home. What earthly matter arises?": "4র্থ হাউস স্থায়ী সম্পদ, জমি এবং বাড়ির আরাম নিয়ন্ত্রণ করে। কি পার্থিব বিষয় উদ্ভূত হয়?",
        "The 6th house dictates your relation to hard physical labor, servants, employees, and those lower in the social hierarchy. How do you manage the toil?": "6 তম ঘর কঠোর শারীরিক শ্রম, চাকর, কর্মচারী এবং সামাজিক শ্রেণিবিন্যাসের নীচের লোকদের সাথে আপনার সম্পর্ককে নির্দেশ করে। আপনি কিভাবে পরিশ্রম পরিচালনা করবেন?",
        "The 6th house governs open enemies, disputes, and royal punishments. What conflict plagues you?": "6 ম ঘর খোলা শত্রু, বিবাদ, এবং রাজকীয় শাস্তি শাসন করে। কোন দ্বন্দ্ব আপনাকে জর্জরিত করে?",
        "The 6th house requires the rhythmic discipline of daily life to suppress diseases and enemies. What needs correction?": "রোগ এবং শত্রুদের দমন করার জন্য 6 ম ঘরের দৈনন্দিন জীবনের ছন্দময় শৃঙ্খলা প্রয়োজন। কি সংশোধন প্রয়োজন?",
        "The 6th house rules Shadripu (the six enemies of the mind). Kama, Krodha, Lobha, Moha, Mada, Matsarya. Which vice has taken the reins?": "ষষ্ঠ ঘর শাদরিপু (মনের ছয় শত্রু) শাসন করে। কাম, ক্রোধ, লোভা, মোহ, মদ, মাৎসার্য। লাগাম টেনে ধরেছে কোন ভাই?",
        "The 6th house tracks the heavy karmic chains of Runa (Debt). Are you bound to creditors, or are others bound to you?": "6 তম বাড়িটি রুনার (ঋণ) এর ভারী কার্মিক চেইনগুলি ট্র্যাক করে। আপনি কি পাওনাদারদের সাথে আবদ্ধ, নাকি অন্যরা আপনার সাথে আবদ্ধ?",
        "The 8th house and D8 chart govern Tantra, hidden dimension, and the manipulation of occult energies. Do you dare look?": "8ম ঘর এবং D8 চার্ট তন্ত্র, লুকানো মাত্রা এবং গুপ্ত শক্তির হেরফের পরিচালনা করে। আপনি সাহস করে দেখুন?",
        "The 8th house rules unearned wealth, buried treasures, and sudden reversals. What hidden matter stirs?": "8ম ঘর অনাগত সম্পদ, সমাহিত ধন, এবং আকস্মিক উল্টে যাওয়া শাসন করে। কি গোপন বিষয় আলোড়ন?",
        "The 9th house connects you to the deep, unshakable roots of your ancestors, language, and cultural rituals. Are you tethered or drifting?": "9ম ঘর আপনাকে আপনার পূর্বপুরুষ, ভাষা এবং সাংস্কৃতিক আচার-অনুষ্ঠানের গভীর, অটল শিকড়ের সাথে সংযুক্ত করে। আপনি tethered বা প্রবাহিত হয়?",
        "The Arudha Lagna dictates the Maya—how the world perceives your status and renown. What is your public aim?": "অরুধা লগ্ন মায়াকে নির্দেশ করে - কীভাবে বিশ্ব আপনার মর্যাদা এবং খ্যাতি উপলব্ধি করে। আপনার পাবলিক লক্ষ্য কি?",
        "The D12 chart reveals the absolute karmic ties to the mother and father. What is the inquiry?": "D12 চার্ট মা এবং বাবার পরম কর্মিক সম্পর্ক প্রকাশ করে। তদন্ত কি?",
        "The D20 charts your spiritual receptivity and readiness for Mantra Diksha. Are you prepared to receive?": "D20 মন্ত্র দীক্ষার জন্য আপনার আধ্যাত্মিক গ্রহণযোগ্যতা এবং প্রস্তুতির তালিকা করে। আপনি গ্রহণ করার জন্য প্রস্তুত?",
        "The D6 map exposes imbalances in the Vata, Pitta, and Kapha doshas. What anomaly requires attention?": "D6 মানচিত্রটি ভাটা, পিট্টা এবং কাফা দোষের ভারসাম্যহীনতা প্রকাশ করে। কি অসঙ্গতি মনোযোগ প্রয়োজন?",
        "The Maraka (Death-inflicting) houses command periods of immense physical danger. Scan for immediate threats.": "মারাকা (মৃত্যু-ঘটিত) ঘরগুলি প্রচুর শারীরিক বিপদের আদেশ দেয়। তাৎক্ষণিক হুমকির জন্য স্ক্যান করুন।",
        "The expansion of the bloodline is governed by the 5th house. What concerns the legacy of your lineage?": "রক্তরেখার সম্প্রসারণ 5ম ঘর দ্বারা পরিচালিত হয়। কি আপনার বংশের উত্তরাধিকার উদ্বেগ?",
        "The foundation of life rests upon Righteousness (Dharma). Which aspect of duty seeks clarity?": "জীবনের ভিত্তি ধার্মিকতার (ধর্ম) উপর নির্ভর করে। কর্তব্যের কোন দিকটি স্পষ্টতা চায়?",
        "The management of beasts, pets, and agricultural livestock falls under the 6th house. How is your relationship with the silent beings?": "পশু, পোষা প্রাণী, এবং কৃষি পশুসম্পদ ব্যবস্থাপনা 6 তম ঘরের অধীনে পড়ে। নীরব প্রাণীদের সাথে আপনার সম্পর্ক কেমন?",
        "The pursuit of Vidya removes darkness. What intellectual or spiritual knowledge do you seek?": "বিদ্যার সাধনা অন্ধকার দূর করে। আপনি কি বুদ্ধিবৃত্তিক বা আধ্যাত্মিক জ্ঞান খুঁজছেন?",
        "The sacred union of Vivaha binds two souls karmically. What is your inquiry regarding marital bonds?": "বিবাহের পবিত্র মিলন দুটি আত্মাকে কর্ম্মভাবে আবদ্ধ করে। বৈবাহিক বন্ধন সম্পর্কে আপনার জিজ্ঞাসা কি?",
        "The subconscious mind receives signals from the astral plane. What omens are manifesting?": "অবচেতন মন অ্যাস্ট্রাল প্লেন থেকে সংকেত গ্রহণ করে। কি লক্ষণ প্রকাশ পাচ্ছে?",
        "The ultimate aim is liberation from the cycle of birth and death. What blocks your spiritual ascent?": "চূড়ান্ত লক্ষ্য জন্ম-মৃত্যুর চক্র থেকে মুক্তি। কি আপনার আধ্যাত্মিক আরোহন ব্লক?",
        "Travel for spiritual merit or foreign expansion requires alignment. What is the nature of the journey?": "আধ্যাত্মিক যোগ্যতা বা বিদেশী সম্প্রসারণের জন্য ভ্রমণের জন্য সারিবদ্ধতা প্রয়োজন। যাত্রা প্রকৃতি কি?",
        "True wealth is internal peace (Sukha) and a harmonious home. What disturbs the waters of the mind?": "প্রকৃত সম্পদ হল অভ্যন্তরীণ শান্তি (সুখা) এবং একটি সুরেলা ঘর। মনের জলে কি বিরক্তি?",
        "We carry the unsolved debts of our forefathers. What ancestral affliction requires propitiation?": "আমরা আমাদের পূর্বপুরুষদের অমীমাংসিত ঋণ বহন. কোন পৈতৃক দুঃখের জন্য প্রায়শ্চিত্তের প্রয়োজন?",
        "Wealth that is hoarded rots the soul. Danam (Charity) is the great purifier of the D2 treasury. Where must your resources flow?": "মজুতকৃত সম্পদ আত্মাকে পচে যায়। দানম (চ্যারিটি) হল D2 কোষাগারের মহান পরিশোধক। আপনার সম্পদ কোথায় প্রবাহিত করা উচিত?"
    },
    "sa": {
        "10th House Karma": "१० गृह कर्म",
        "11th House Bonds": "11th House Bonds",
        "11th House Gains": "११ तमः गृहः लाभः",
        "12th/5th House Release": "१२/५ सदन विमोचन",
        "12th/9th House Vectors": "१२/९ गृह सदिश",
        "2nd House Sustenance": "2nd House पोषण",
        "3rd/5th House Skills": "3rd/5th House कौशलम्",
        "4th House Mobility": "चतुर्थ गृह गतिशीलता",
        "4th House Tranquility": "चतुर्थ गृह शान्ति",
        "6th House Afflictions": "6th House क्लेशाः",
        "6th House Companions": "षष्ठ सदन सहचर",
        "6th House Discipline": "षष्ठ गृह अनुशासन",
        "6th House Ledgers": "6th House Ledgers",
        "6th/Saturn Karma": "6 वी/शनि कर्म",
        "8th House Mysteries": "८ गृह रहस्य",
        "9th House Philanthropy": "९ वी गृह परोपकार",
        "9th House Roots": "९ गृहमूलम्",
        "Afflictions demand propitiation. Which traditional remedial measure do you seek to enact?": "क्लेशाः प्रायश्चित्तं आग्रहयन्ति। भवान् कः पारम्परिकः उपायः प्रवर्तयितुं इच्छति ?",
        "Arudha Lagna Profile": "अरुधा लग्न प्रोफाइल",
        "Between the grinding gears of Dharma and Artha, the soul requires Vishrama (rest) and playful release to maintain sanity. How do you retreat?": "धर्मार्थयोः पेषणयन्त्रयोः मध्ये आत्मा विवेकं निर्वाहयितुम् विश्रमस्य (विश्रामस्य) लीलाविमोचनस्य च आवश्यकतां अनुभवति। कथं निवर्तसे ?",
        "D12 Dwadasamsa": "D12 द्वादसम्सा",
        "D2 Hora Liquidity": "D2 होरा तरलता",
        "D20 Vimsamsa": "D20 विमसंसा",
        "D24 Chaturvimsamsa": "D24 चतुर्विमसंसा",
        "D3 Drekkana": "D3 द्रेक्कना",
        "D30 Trimsamsa": "D30 त्रिम्संसा",
        "D4 Chaturthamsa": "D4 चतुर्थम्सा",
        "D40 Khavedamsa": "D40 खवेदम्सा",
        "D6 Bodily Humors": "D6 शारीरिक हास्य",
        "D60 Shashtiamsa": "D60 षष्ठीअम्सा",
        "D7 Saptamsa Matrix": "D7 सप्तम्सा मैट्रिक्स",
        "D8 Ashtamsa Matrix": "D8 अष्टमसा मैट्रिक्स",
        "D9 & 9th House Rectitude": "D9 & 9th House Rectitude",
        "D9 Navamsa Harmony": "D9 नवमसा सद्भावः",
        "Dosha Mitigation": "दोष शमन",
        "Maraka & Badhaka": "मरका एवं बधका",
        "Muhurta aligns human action with divine time. What auspicious event are you planning?": "मुहूर्तः मानवकर्मं दिव्यकालेन सह संरेखयति। किं शुभं आयोजनं भवन्तः योजनां कुर्वन्ति ?",
        "Panchanga Engine": "पंचंगा इञ्जिन",
        "Swapna Shastra": "स्वप्न शास्त्र",
        "The 10th house governs your livelihood, daily trade, and standing before employers. What is the state of your work?": "१० तमः गृहः भवतः आजीविकायाः, दैनन्दिनव्यापारस्य, नियोक्तृणां समक्षं स्थापनं च नियन्त्रयति । भवतः कार्यस्य का स्थितिः ?",
        "The 11th house dictates your ability to extract wealth and favors from large societies or guilds. What is the objective?": "११ तमः गृहः बृहत् समाजेभ्यः अथवा गिल्ड्-भ्यः धनं, अनुग्रहं च निष्कासयितुं भवतः क्षमतां निर्दिशति । किं प्रयोजनम् ?",
        "The 11th house signifies the networks and companions we choose. Are your friends true allies or hidden drains?": "११ तमः गृहः वयं यत् जालं, सहचराः च चिनोमः तत् सूचयति । किं भवतः मित्राणि सत्यानि मित्राणि सन्ति वा गुप्तनालिकाः सन्ति?",
        "The 2nd house and D2 chart govern accumulated treasures, gold, and grains. What is your material focus?": "द्वितीयगृहं D2 चार्टं च सञ्चितनिधिं, सुवर्णं, धान्यं च नियन्त्रयति । भवतः भौतिककेन्द्रीकरणं किम् ?",
        "The 2nd house rules what enters the mouth. Diet directly shapes consciousness and physical destiny. What are you consuming?": "मुखं यत् प्रविशति तत् द्वितीयं गृहं शासयति। आहारः प्रत्यक्षतया चैतन्यं शारीरिकं दैवं च आकारयति। किं उपभोजसि ?",
        "The 3rd house governs the hands; the 5th governs creative intelligence. Are you honing your innate God-given skills?": "तृतीयं गृहं हस्तान् शासयति; ५ तमः सृजनात्मकबुद्धिं नियन्त्रयति । किं भवन्तः स्वस्य सहजं ईश्वरप्रदत्तं कौशलं निखारयन्ति?",
        "The 3rd house rules valor (Parakrama), siblings, and the right arm. Where is your courage directed?": "तृतीयं गृहं शौर्यं (परक्रमं), भ्रातरः, दक्षिणबाहुं च शासयति। भवतः साहसं कुत्र निर्दिश्यते ?",
        "The 4th house and Venus dictate your comfort in travel, ownership of vehicles, beasts of burden, and daily transport. Is your carriage secure?": "चतुर्थगृहं शुक्रं च यात्रायां, वाहनानां स्वामित्वं, भारपशवः, दैनन्दिनयानस्य च भवतः आरामं निर्दिशन्ति । भवतः यानं सुरक्षितम् अस्ति वा ?",
        "The 4th house governs fixed assets, land, and the comfort of the home. What earthly matter arises?": "चतुर्थगृहं स्थिरसम्पत्तयः, भूमिः, गृहस्य आरामं च नियन्त्रयति । किं पार्थिवं पदार्थं उत्पद्यते ?",
        "The 6th house dictates your relation to hard physical labor, servants, employees, and those lower in the social hierarchy. How do you manage the toil?": "6 तमः गृहः कठिनशारीरिकश्रमस्य, सेवकानां, कर्मचारिणां, सामाजिकपदानुक्रमे निम्नतमानां च सह भवतः सम्बन्धं निर्दिशति। भवन्तः कथं परिश्रमं प्रबन्धयन्ति ?",
        "The 6th house governs open enemies, disputes, and royal punishments. What conflict plagues you?": "६ तमः गृहः मुक्तशत्रवः, विवादाः, राजदण्डाः च नियन्त्रयति । कः विग्रहः भवन्तं पीडयति ?",
        "The 6th house requires the rhythmic discipline of daily life to suppress diseases and enemies. What needs correction?": "६ गृहे रोगशत्रुनिरोधाय दैनन्दिनजीवनस्य लयात्मकानुशासनस्य आवश्यकता भवति । किं संशोधनस्य आवश्यकता अस्ति ?",
        "The 6th house rules Shadripu (the six enemies of the mind). Kama, Krodha, Lobha, Moha, Mada, Matsarya. Which vice has taken the reins?": "षट् गृहं शाद्रीपुं (चित्तस्य षट् शत्रून्) शासति। कामः क्रोधः लोभः मोहः मदः मत्स्यः | कः दुष्टः बागडोरं गृहीतवान् ?",
        "The 6th house tracks the heavy karmic chains of Runa (Debt). Are you bound to creditors, or are others bound to you?": "६ तमः गृहः रुणस्य (ऋणस्य) गुरुकर्मशृङ्खलानां अनुसरणं करोति । किं भवन्तः ऋणदातृभिः सह बद्धाः सन्ति, अन्ये वा बद्धाः सन्ति?",
        "The 8th house and D8 chart govern Tantra, hidden dimension, and the manipulation of occult energies. Do you dare look?": "८ गृहं D8 चार्टं च तन्त्रं, गुप्तं आयामं, गुप्तशक्तयः हेरफेरं च नियन्त्रयन्ति । किं त्वं पश्यितुं साहसं करोषि ?",
        "The 8th house rules unearned wealth, buried treasures, and sudden reversals. What hidden matter stirs?": "८ गृहं अनर्जितधनं, दफननिधिः, आकस्मिकविपर्ययः च शासनं करोति । किं गुप्तं द्रव्यं क्षोभयति ?",
        "The 9th house connects you to the deep, unshakable roots of your ancestors, language, and cultural rituals. Are you tethered or drifting?": "९ तमः गृहः भवन्तं भवतः पूर्वजानां, भाषायाः, सांस्कृतिकसंस्कारस्य च गहनैः, अचञ्चलमूलैः सह सम्बध्दयति । किं त्वं बद्धः असि वा भ्रमसि वा ?",
        "The Arudha Lagna dictates the Maya—how the world perceives your status and renown. What is your public aim?": "अरुधा लग्नं मायाम् आज्ञापयति—जगत् भवतः स्थितिं यशः च कथं गृह्णाति। भवतः सार्वजनिकं लक्ष्यं किम् ?",
        "The D12 chart reveals the absolute karmic ties to the mother and father. What is the inquiry?": "D12 चार्ट् मातुः पितुः च निरपेक्षकर्मसम्बन्धं प्रकाशयति। का जिज्ञासा?",
        "The D20 charts your spiritual receptivity and readiness for Mantra Diksha. Are you prepared to receive?": "D20 भवतः आध्यात्मिकग्राहकताम्, मन्त्रदीक्षस्य सज्जतां च चार्टं करोति। किं भवन्तः प्राप्तुं सज्जाः सन्ति ?",
        "The D6 map exposes imbalances in the Vata, Pitta, and Kapha doshas. What anomaly requires attention?": "D6 मानचित्रे वात-पित्त-कफा-दोषेषु असन्तुलनं प्रकाशयति । का विसंगतिः ध्यानस्य आवश्यकतां जनयति ?",
        "The Maraka (Death-inflicting) houses command periods of immense physical danger. Scan for immediate threats.": "मरक (मृत्यु-प्रवर्तक) गृहाणि अपार-शारीरिक-संकटस्य अवधिं आज्ञापयन्ति । तत्कालं धमकीनां कृते स्कैन् कुर्वन्तु।",
        "The expansion of the bloodline is governed by the 5th house. What concerns the legacy of your lineage?": "रक्तरेखायाः विस्तारः ५ गृहेण नियन्त्रितः भवति । भवतः वंशस्य विरासतां विषये किं वर्तते ?",
        "The foundation of life rests upon Righteousness (Dharma). Which aspect of duty seeks clarity?": "जीवनस्य आधारः धर्मे (धर्मे) अवलम्बते। कर्तव्यस्य कः पक्षः स्पष्टतां याचते ?",
        "The management of beasts, pets, and agricultural livestock falls under the 6th house. How is your relationship with the silent beings?": "पशवः, पालतूपजीविनां, कृषिपशुपालनानां च प्रबन्धनं ६ गृहस्य अन्तर्गतं भवति । मौनभूतैः सह भवतः कथं सम्बन्धः ?",
        "The pursuit of Vidya removes darkness. What intellectual or spiritual knowledge do you seek?": "विद्यायाः अनुसरणेन तमः अपहरति। किं बौद्धिकं आध्यात्मिकं वा ज्ञानं अन्विष्यसि ?",
        "The sacred union of Vivaha binds two souls karmically. What is your inquiry regarding marital bonds?": "विवाहस्य पवित्रः संयोगः द्वौ आत्मानं कर्मणा बध्नाति। वैवाहिकबन्धनविषये भवतः का जिज्ञासा ?",
        "The subconscious mind receives signals from the astral plane. What omens are manifesting?": "अवचेतनं मनः सूक्ष्मविमानात् संकेतान् प्राप्नोति । के शगुनाः प्रकट्यन्ते ?",
        "The ultimate aim is liberation from the cycle of birth and death. What blocks your spiritual ascent?": "जन्ममरणचक्रात् मुक्तिः एव परमं लक्ष्यम् । भवतः आध्यात्मिकं आरोहणं किं अवरुद्धं करोति ?",
        "Travel for spiritual merit or foreign expansion requires alignment. What is the nature of the journey?": "आध्यात्मिकपुण्यार्थं विदेशविस्तारार्थं वा यात्रायां संरेखणस्य आवश्यकता भवति। यात्रायाः स्वरूपं कः ?",
        "True wealth is internal peace (Sukha) and a harmonious home. What disturbs the waters of the mind?": "सत्यं धनं आन्तरिकं शान्तिं (सुखं) सौहार्दं गृहं च। मनसः जलं किं बाधते ?",
        "We carry the unsolved debts of our forefathers. What ancestral affliction requires propitiation?": "वयं पितृणां असमाधानं ऋणं वहामः। किं पैतृकदुःखं प्रायश्चित्तं अपेक्षते ?",
        "Wealth that is hoarded rots the soul. Danam (Charity) is the great purifier of the D2 treasury. Where must your resources flow?": "संचितं धनं आत्मानं जर्जयति। दानम् (दानम्) इति डी२ कोषस्य महाशुद्धिकरणम् । भवतः संसाधनानाम् प्रवाहः कुत्र भवितुमर्हति ?"
    }
};

const filePath = 'src/i18n/dynamicTranslations.js';
let content = fs.readFileSync(filePath, 'utf8');

for (const [lang, dict] of Object.entries(UI_TEXT)) {
    const langMarkerFull = `  ${lang}: {\n`;
    const langMarkerAlt = `${lang}: {`;
    
    let idx = content.indexOf(langMarkerFull);
    let markerLength = langMarkerFull.length;
    
    if (idx === -1) {
        idx = content.indexOf(langMarkerAlt);
        markerLength = langMarkerAlt.length;
    }

    if (idx !== -1) {
        let insertStr = '';
        for (const [k, v] of Object.entries(dict)) {
            if (!content.slice(idx, idx + 60000).includes(`"${k}"`)) {
                insertStr += `    "${k}": "${v.replace(/"/g, '\\"')}",\n`;
            }
        }
        
        if (insertStr) {
            content = content.slice(0, idx + markerLength) + insertStr + content.slice(idx + markerLength);
        }
    }
}
fs.writeFileSync(filePath, content);
console.log("Successfully injected translated descriptions into dynamicTranslations.js via auto-translate node.");
